/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AppChangesParams,
  CompetitorChangesParams,
  PaginatedChangeResponse
} from '../../models';

import { orvalMutator } from '../../../lib/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List store listing changes for all tracked apps
 */
export const appChanges = (
    params?: AppChangesParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<PaginatedChangeResponse>(
      {url: `/changes/apps`, method: 'GET',
        params, signal
    },
      options);
    }




export const getAppChangesQueryKey = (params?: AppChangesParams,) => {
    return [
    `/changes/apps`, ...(params ? [params] : [])
    ] as const;
    }


export const getAppChangesQueryOptions = <TData = Awaited<ReturnType<typeof appChanges>>, TError = unknown>(params?: AppChangesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appChanges>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAppChangesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof appChanges>>> = ({ signal }) => appChanges(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appChanges>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AppChangesQueryResult = NonNullable<Awaited<ReturnType<typeof appChanges>>>
export type AppChangesQueryError = unknown


export function useAppChanges<TData = Awaited<ReturnType<typeof appChanges>>, TError = unknown>(
 params: undefined |  AppChangesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof appChanges>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof appChanges>>,
          TError,
          Awaited<ReturnType<typeof appChanges>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppChanges<TData = Awaited<ReturnType<typeof appChanges>>, TError = unknown>(
 params?: AppChangesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appChanges>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof appChanges>>,
          TError,
          Awaited<ReturnType<typeof appChanges>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppChanges<TData = Awaited<ReturnType<typeof appChanges>>, TError = unknown>(
 params?: AppChangesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appChanges>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List store listing changes for all tracked apps
 */

export function useAppChanges<TData = Awaited<ReturnType<typeof appChanges>>, TError = unknown>(
 params?: AppChangesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appChanges>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppChangesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary List store listing changes for all competitor apps
 */
export const competitorChanges = (
    params?: CompetitorChangesParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<PaginatedChangeResponse>(
      {url: `/changes/competitors`, method: 'GET',
        params, signal
    },
      options);
    }




export const getCompetitorChangesQueryKey = (params?: CompetitorChangesParams,) => {
    return [
    `/changes/competitors`, ...(params ? [params] : [])
    ] as const;
    }


export const getCompetitorChangesQueryOptions = <TData = Awaited<ReturnType<typeof competitorChanges>>, TError = unknown>(params?: CompetitorChangesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof competitorChanges>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCompetitorChangesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof competitorChanges>>> = ({ signal }) => competitorChanges(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof competitorChanges>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CompetitorChangesQueryResult = NonNullable<Awaited<ReturnType<typeof competitorChanges>>>
export type CompetitorChangesQueryError = unknown


export function useCompetitorChanges<TData = Awaited<ReturnType<typeof competitorChanges>>, TError = unknown>(
 params: undefined |  CompetitorChangesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof competitorChanges>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof competitorChanges>>,
          TError,
          Awaited<ReturnType<typeof competitorChanges>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCompetitorChanges<TData = Awaited<ReturnType<typeof competitorChanges>>, TError = unknown>(
 params?: CompetitorChangesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof competitorChanges>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof competitorChanges>>,
          TError,
          Awaited<ReturnType<typeof competitorChanges>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCompetitorChanges<TData = Awaited<ReturnType<typeof competitorChanges>>, TError = unknown>(
 params?: CompetitorChangesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof competitorChanges>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List store listing changes for all competitor apps
 */

export function useCompetitorChanges<TData = Awaited<ReturnType<typeof competitorChanges>>, TError = unknown>(
 params?: CompetitorChangesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof competitorChanges>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCompetitorChangesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




