/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ExploreIcons200,
  ExploreIconsParams,
  ExploreScreenshots200,
  ExploreScreenshotsParams
} from '../../models';

import { orvalMutator } from '../../../lib/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Browse screenshots across all apps
 */
export const exploreScreenshots = (
    params?: ExploreScreenshotsParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<ExploreScreenshots200>(
      {url: `/explorer/screenshots`, method: 'GET',
        params, signal
    },
      options);
    }




export const getExploreScreenshotsQueryKey = (params?: ExploreScreenshotsParams,) => {
    return [
    `/explorer/screenshots`, ...(params ? [params] : [])
    ] as const;
    }


export const getExploreScreenshotsQueryOptions = <TData = Awaited<ReturnType<typeof exploreScreenshots>>, TError = unknown>(params?: ExploreScreenshotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exploreScreenshots>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getExploreScreenshotsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof exploreScreenshots>>> = ({ signal }) => exploreScreenshots(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof exploreScreenshots>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExploreScreenshotsQueryResult = NonNullable<Awaited<ReturnType<typeof exploreScreenshots>>>
export type ExploreScreenshotsQueryError = unknown


export function useExploreScreenshots<TData = Awaited<ReturnType<typeof exploreScreenshots>>, TError = unknown>(
 params: undefined |  ExploreScreenshotsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof exploreScreenshots>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof exploreScreenshots>>,
          TError,
          Awaited<ReturnType<typeof exploreScreenshots>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExploreScreenshots<TData = Awaited<ReturnType<typeof exploreScreenshots>>, TError = unknown>(
 params?: ExploreScreenshotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exploreScreenshots>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof exploreScreenshots>>,
          TError,
          Awaited<ReturnType<typeof exploreScreenshots>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExploreScreenshots<TData = Awaited<ReturnType<typeof exploreScreenshots>>, TError = unknown>(
 params?: ExploreScreenshotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exploreScreenshots>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Browse screenshots across all apps
 */

export function useExploreScreenshots<TData = Awaited<ReturnType<typeof exploreScreenshots>>, TError = unknown>(
 params?: ExploreScreenshotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exploreScreenshots>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getExploreScreenshotsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Browse app icons across all apps
 */
export const exploreIcons = (
    params?: ExploreIconsParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<ExploreIcons200>(
      {url: `/explorer/icons`, method: 'GET',
        params, signal
    },
      options);
    }




export const getExploreIconsQueryKey = (params?: ExploreIconsParams,) => {
    return [
    `/explorer/icons`, ...(params ? [params] : [])
    ] as const;
    }


export const getExploreIconsQueryOptions = <TData = Awaited<ReturnType<typeof exploreIcons>>, TError = unknown>(params?: ExploreIconsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exploreIcons>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getExploreIconsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof exploreIcons>>> = ({ signal }) => exploreIcons(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof exploreIcons>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExploreIconsQueryResult = NonNullable<Awaited<ReturnType<typeof exploreIcons>>>
export type ExploreIconsQueryError = unknown


export function useExploreIcons<TData = Awaited<ReturnType<typeof exploreIcons>>, TError = unknown>(
 params: undefined |  ExploreIconsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof exploreIcons>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof exploreIcons>>,
          TError,
          Awaited<ReturnType<typeof exploreIcons>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExploreIcons<TData = Awaited<ReturnType<typeof exploreIcons>>, TError = unknown>(
 params?: ExploreIconsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exploreIcons>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof exploreIcons>>,
          TError,
          Awaited<ReturnType<typeof exploreIcons>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExploreIcons<TData = Awaited<ReturnType<typeof exploreIcons>>, TError = unknown>(
 params?: ExploreIconsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exploreIcons>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Browse app icons across all apps
 */

export function useExploreIcons<TData = Awaited<ReturnType<typeof exploreIcons>>, TError = unknown>(
 params?: ExploreIconsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exploreIcons>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getExploreIconsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




