/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiTokenCreatedResource,
  ApiTokenResource,
  MessageResource,
  PasswordUpdateRequest,
  ProfileDeleteRequest,
  ProfileUpdateRequest,
  StoreApiTokenRequest,
  UserResource
} from '../../models';

import { orvalMutator } from '../../../lib/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List all API tokens
 */
export const listApiTokens = (

 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<ApiTokenResource[]>(
      {url: `/account/api-tokens`, method: 'GET', signal
    },
      options);
    }




export const getListApiTokensQueryKey = () => {
    return [
    `/account/api-tokens`
    ] as const;
    }


export const getListApiTokensQueryOptions = <TData = Awaited<ReturnType<typeof listApiTokens>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listApiTokens>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListApiTokensQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listApiTokens>>> = ({ signal }) => listApiTokens(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listApiTokens>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListApiTokensQueryResult = NonNullable<Awaited<ReturnType<typeof listApiTokens>>>
export type ListApiTokensQueryError = unknown


export function useListApiTokens<TData = Awaited<ReturnType<typeof listApiTokens>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listApiTokens>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listApiTokens>>,
          TError,
          Awaited<ReturnType<typeof listApiTokens>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListApiTokens<TData = Awaited<ReturnType<typeof listApiTokens>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listApiTokens>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listApiTokens>>,
          TError,
          Awaited<ReturnType<typeof listApiTokens>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListApiTokens<TData = Awaited<ReturnType<typeof listApiTokens>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listApiTokens>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all API tokens
 */

export function useListApiTokens<TData = Awaited<ReturnType<typeof listApiTokens>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listApiTokens>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListApiTokensQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create a new API token
 */
export const createApiToken = (
    storeApiTokenRequest: StoreApiTokenRequest,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<ApiTokenCreatedResource>(
      {url: `/account/api-tokens`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: storeApiTokenRequest, signal
    },
      options);
    }



export const getCreateApiTokenMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createApiToken>>, TError,{data: StoreApiTokenRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof createApiToken>>, TError,{data: StoreApiTokenRequest}, TContext> => {

const mutationKey = ['createApiToken'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createApiToken>>, {data: StoreApiTokenRequest}> = (props) => {
          const {data} = props ?? {};

          return  createApiToken(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateApiTokenMutationResult = NonNullable<Awaited<ReturnType<typeof createApiToken>>>
    export type CreateApiTokenMutationBody = StoreApiTokenRequest
    export type CreateApiTokenMutationError = void

    /**
 * @summary Create a new API token
 */
export const useCreateApiToken = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createApiToken>>, TError,{data: StoreApiTokenRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createApiToken>>,
        TError,
        {data: StoreApiTokenRequest},
        TContext
      > => {
      return useMutation(getCreateApiTokenMutationOptions(options), queryClient);
    }
    /**
 * @summary Revoke an API token
 */
export const revokeApiToken = (
    tokenId: number,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<void>(
      {url: `/account/api-tokens/${tokenId}`, method: 'DELETE', signal
    },
      options);
    }



export const getRevokeApiTokenMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeApiToken>>, TError,{tokenId: number}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof revokeApiToken>>, TError,{tokenId: number}, TContext> => {

const mutationKey = ['revokeApiToken'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof revokeApiToken>>, {tokenId: number}> = (props) => {
          const {tokenId} = props ?? {};

          return  revokeApiToken(tokenId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RevokeApiTokenMutationResult = NonNullable<Awaited<ReturnType<typeof revokeApiToken>>>

    export type RevokeApiTokenMutationError = void

    /**
 * @summary Revoke an API token
 */
export const useRevokeApiToken = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeApiToken>>, TError,{tokenId: number}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof revokeApiToken>>,
        TError,
        {tokenId: number},
        TContext
      > => {
      return useMutation(getRevokeApiTokenMutationOptions(options), queryClient);
    }
    /**
 * @summary Get authenticated user profile
 */
export const showProfile = (

 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<UserResource>(
      {url: `/account/profile`, method: 'GET', signal
    },
      options);
    }




export const getShowProfileQueryKey = () => {
    return [
    `/account/profile`
    ] as const;
    }


export const getShowProfileQueryOptions = <TData = Awaited<ReturnType<typeof showProfile>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showProfile>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getShowProfileQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof showProfile>>> = ({ signal }) => showProfile(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof showProfile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ShowProfileQueryResult = NonNullable<Awaited<ReturnType<typeof showProfile>>>
export type ShowProfileQueryError = unknown


export function useShowProfile<TData = Awaited<ReturnType<typeof showProfile>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof showProfile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof showProfile>>,
          TError,
          Awaited<ReturnType<typeof showProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useShowProfile<TData = Awaited<ReturnType<typeof showProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showProfile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof showProfile>>,
          TError,
          Awaited<ReturnType<typeof showProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useShowProfile<TData = Awaited<ReturnType<typeof showProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showProfile>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get authenticated user profile
 */

export function useShowProfile<TData = Awaited<ReturnType<typeof showProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showProfile>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getShowProfileQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Delete user account
 */
export const deleteProfile = (
    profileDeleteRequest: ProfileDeleteRequest,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<void>(
      {url: `/account/profile`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: profileDeleteRequest, signal
    },
      options);
    }



export const getDeleteProfileMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProfile>>, TError,{data: ProfileDeleteRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteProfile>>, TError,{data: ProfileDeleteRequest}, TContext> => {

const mutationKey = ['deleteProfile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProfile>>, {data: ProfileDeleteRequest}> = (props) => {
          const {data} = props ?? {};

          return  deleteProfile(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteProfileMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProfile>>>
    export type DeleteProfileMutationBody = ProfileDeleteRequest
    export type DeleteProfileMutationError = unknown

    /**
 * @summary Delete user account
 */
export const useDeleteProfile = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProfile>>, TError,{data: ProfileDeleteRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProfile>>,
        TError,
        {data: ProfileDeleteRequest},
        TContext
      > => {
      return useMutation(getDeleteProfileMutationOptions(options), queryClient);
    }
    /**
 * @summary Update user profile
 */
export const updateProfile = (
    profileUpdateRequest: ProfileUpdateRequest,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<UserResource>(
      {url: `/account/profile`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: profileUpdateRequest, signal
    },
      options);
    }



export const getUpdateProfileMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProfile>>, TError,{data: ProfileUpdateRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof updateProfile>>, TError,{data: ProfileUpdateRequest}, TContext> => {

const mutationKey = ['updateProfile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProfile>>, {data: ProfileUpdateRequest}> = (props) => {
          const {data} = props ?? {};

          return  updateProfile(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateProfileMutationResult = NonNullable<Awaited<ReturnType<typeof updateProfile>>>
    export type UpdateProfileMutationBody = ProfileUpdateRequest
    export type UpdateProfileMutationError = void

    /**
 * @summary Update user profile
 */
export const useUpdateProfile = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProfile>>, TError,{data: ProfileUpdateRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProfile>>,
        TError,
        {data: ProfileUpdateRequest},
        TContext
      > => {
      return useMutation(getUpdateProfileMutationOptions(options), queryClient);
    }
    /**
 * @summary Update user password
 */
export const updatePassword = (
    passwordUpdateRequest: PasswordUpdateRequest,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<MessageResource>(
      {url: `/account/password`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: passwordUpdateRequest, signal
    },
      options);
    }



export const getUpdatePasswordMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePassword>>, TError,{data: PasswordUpdateRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof updatePassword>>, TError,{data: PasswordUpdateRequest}, TContext> => {

const mutationKey = ['updatePassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePassword>>, {data: PasswordUpdateRequest}> = (props) => {
          const {data} = props ?? {};

          return  updatePassword(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdatePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof updatePassword>>>
    export type UpdatePasswordMutationBody = PasswordUpdateRequest
    export type UpdatePasswordMutationError = void

    /**
 * @summary Update user password
 */
export const useUpdatePassword = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePassword>>, TError,{data: PasswordUpdateRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePassword>>,
        TError,
        {data: PasswordUpdateRequest},
        TContext
      > => {
      return useMutation(getUpdatePasswordMutationOptions(options), queryClient);
    }
