/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    staff: StaffAuthOperations;
  };
  blocks: {};
  collections: {
    staff: Staff;
    members: Member;
    countries: Country;
    'store-categories': StoreCategory;
    publishers: Publisher;
    'catalog-apps': CatalogApp;
    'app-versions': AppVersion;
    'app-listings': AppListing;
    'app-metrics': AppMetric;
    'connector-configs': ConnectorConfig;
    'sync-tasks': SyncTask;
    'task-attempts': TaskAttempt;
    'collection-runs': CollectionRun;
    'dead-letters': DeadLetter;
    'ad-advertisers': AdAdvertiser;
    ads: Ad;
    'ad-assets': AdAsset;
    'ad-app-links': AdAppLink;
    'payload-media': PayloadMedia;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    staff: StaffSelect<false> | StaffSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    countries: CountriesSelect<false> | CountriesSelect<true>;
    'store-categories': StoreCategoriesSelect<false> | StoreCategoriesSelect<true>;
    publishers: PublishersSelect<false> | PublishersSelect<true>;
    'catalog-apps': CatalogAppsSelect<false> | CatalogAppsSelect<true>;
    'app-versions': AppVersionsSelect<false> | AppVersionsSelect<true>;
    'app-listings': AppListingsSelect<false> | AppListingsSelect<true>;
    'app-metrics': AppMetricsSelect<false> | AppMetricsSelect<true>;
    'connector-configs': ConnectorConfigsSelect<false> | ConnectorConfigsSelect<true>;
    'sync-tasks': SyncTasksSelect<false> | SyncTasksSelect<true>;
    'task-attempts': TaskAttemptsSelect<false> | TaskAttemptsSelect<true>;
    'collection-runs': CollectionRunsSelect<false> | CollectionRunsSelect<true>;
    'dead-letters': DeadLettersSelect<false> | DeadLettersSelect<true>;
    'ad-advertisers': AdAdvertisersSelect<false> | AdAdvertisersSelect<true>;
    ads: AdsSelect<false> | AdsSelect<true>;
    'ad-assets': AdAssetsSelect<false> | AdAssetsSelect<true>;
    'ad-app-links': AdAppLinksSelect<false> | AdAppLinksSelect<true>;
    'payload-media': PayloadMediaSelect<false> | PayloadMediaSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Staff;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface StaffAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff".
 */
export interface Staff {
  id: number;
  name: string;
  role: 'super-admin' | 'operator';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'staff';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  name: string;
  email: string;
  emailVerifiedAt?: string | null;
  passwordHash: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries".
 */
export interface Country {
  id: string;
  name: string;
  emoji?: string | null;
  isActiveIos?: boolean | null;
  isActiveAndroid?: boolean | null;
  iosLanguages?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  androidLanguages?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  priority?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-categories".
 */
export interface StoreCategory {
  id: number;
  platform: 'ios' | 'android';
  externalId?: string | null;
  name: string;
  slug: string;
  type: 'app' | 'game' | 'magazine';
  parent?: (number | null) | StoreCategory;
  priority?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publishers".
 */
export interface Publisher {
  id: number;
  platform: 'ios' | 'android';
  externalId: string;
  name: string;
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-apps".
 */
export interface CatalogApp {
  id: number;
  platform: 'ios' | 'android';
  externalId: string;
  publisher?: (number | null) | Publisher;
  category?: (number | null) | StoreCategory;
  displayName: string;
  iconUrl?: string | null;
  originCountryCode: string;
  supportedLocales?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  originalReleaseDate?: string | null;
  isFree?: boolean | null;
  discoveredFrom: string;
  discoveredAt: string;
  lastSyncedAt?: string | null;
  isAvailable?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-versions".
 */
export interface AppVersion {
  id: number;
  app: number | CatalogApp;
  version: string;
  releaseDate?: string | null;
  whatsNew?: string | null;
  fileSizeBytes?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-listings".
 */
export interface AppListing {
  id: number;
  app: number | CatalogApp;
  version?: (number | null) | AppVersion;
  locale: string;
  title: string;
  subtitle?: string | null;
  promotionalText?: string | null;
  description: string;
  whatsNew?: string | null;
  screenshots?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  iconUrl?: string | null;
  videoUrl?: string | null;
  price?: number | null;
  currency?: string | null;
  fetchedAt: string;
  checksum: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-metrics".
 */
export interface AppMetric {
  id: number;
  app: number | CatalogApp;
  version?: (number | null) | AppVersion;
  countryCode: string;
  date: string;
  rating?: number | null;
  ratingCount?: number | null;
  ratingBreakdown?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  isAvailable?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "connector-configs".
 */
export interface ConnectorConfig {
  id: number;
  label: string;
  source: 'apple' | 'google-play' | 'meta' | 'google' | 'tiktok';
  enabled?: boolean | null;
  transport: 'fetch' | 'api' | 'browser-rendering';
  capabilities?: ('lookup' | 'search' | 'charts' | 'creatives' | 'media')[] | null;
  countries?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  requestsPerMinute?: number | null;
  concurrency?: number | null;
  health?: ('unknown' | 'healthy' | 'limited' | 'failing' | 'disabled') | null;
  lastHealthCode?: string | null;
  lastSuccessAt?: string | null;
  lastFailureAt?: string | null;
  circuitOpenUntil?: string | null;
  secretStatus?: ('not-required' | 'configured' | 'missing' | 'expired') | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sync-tasks".
 */
export interface SyncTask {
  id: number;
  syncStatusId?: number | null;
  taskId: string;
  kind: string;
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status?: ('pending' | 'running' | 'retrying' | 'completed' | 'failed' | 'dead-letter') | null;
  attemptCount?: number | null;
  failureReason?: string | null;
  errorMessage?: string | null;
  availableAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "task-attempts".
 */
export interface TaskAttempt {
  id: number;
  taskId: string;
  attempt: number;
  status: 'running' | 'completed' | 'failed' | 'retrying';
  source?: string | null;
  startedAt: string;
  completedAt?: string | null;
  durationMs?: number | null;
  resultCount?: number | null;
  errorCode?: string | null;
  errorMessage?: string | null;
  rawR2Key?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collection-runs".
 */
export interface CollectionRun {
  id: number;
  targetId: number;
  source: 'meta' | 'google' | 'tiktok';
  reason: string;
  status: 'running' | 'completed' | 'partial' | 'failed' | 'skipped';
  resultCount?: number | null;
  newAdCount?: number | null;
  linkedAppCount?: number | null;
  candidateCount?: number | null;
  errorMessage?: string | null;
  rawR2Key?: string | null;
  startedAt: string;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dead-letters".
 */
export interface DeadLetter {
  id: number;
  taskId: string;
  kind: string;
  source?: string | null;
  status?: ('open' | 'requeued' | 'resolved') | null;
  attemptCount: number;
  errorCode?: string | null;
  errorMessage: string;
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  rawR2Key?: string | null;
  failedAt: string;
  resolvedAt?: string | null;
  resolvedBy?: (number | null) | Staff;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-advertisers".
 */
export interface AdAdvertiser {
  id: number;
  source: 'meta' | 'google' | 'tiktok';
  sourceAdvertiserId?: string | null;
  name: string;
  domain?: string | null;
  sourceUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ads".
 */
export interface Ad {
  id: number;
  source: 'meta' | 'google' | 'tiktok';
  sourceAdId: string;
  advertiser?: (number | null) | AdAdvertiser;
  sourceUrl?: string | null;
  status?: ('active' | 'inactive' | 'removed' | 'unknown') | null;
  headline?: string | null;
  body?: string | null;
  callToAction?: string | null;
  landingUrl?: string | null;
  platforms?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  languages?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  startedAt?: string | null;
  endedAt?: string | null;
  impressionsMin?: number | null;
  impressionsMax?: number | null;
  reachMin?: number | null;
  reachMax?: number | null;
  spendMin?: number | null;
  spendMax?: number | null;
  currency?: string | null;
  firstCollectedAt: string;
  lastCollectedAt: string;
  rawR2Key?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-assets".
 */
export interface AdAsset {
  id: number;
  sha256: string;
  r2Key: string;
  mediaType: 'image' | 'video' | 'thumbnail';
  mimeType: string;
  byteSize: number;
  width?: number | null;
  height?: number | null;
  durationMs?: number | null;
  originalUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-app-links".
 */
export interface AdAppLink {
  id: number;
  ad: number | Ad;
  app?: (number | null) | CatalogApp;
  candidateName?: string | null;
  confidence: 'certain' | 'strong' | 'candidate';
  matchReason: string;
  verified?: boolean | null;
  verifiedBy?: (number | null) | Staff;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-media".
 */
export interface PayloadMedia {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  actor?: (number | null) | Staff;
  action: string;
  entityType: string;
  entityId?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'staff';
        value: number | Staff;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'countries';
        value: string | Country;
      } | null)
    | ({
        relationTo: 'store-categories';
        value: number | StoreCategory;
      } | null)
    | ({
        relationTo: 'publishers';
        value: number | Publisher;
      } | null)
    | ({
        relationTo: 'catalog-apps';
        value: number | CatalogApp;
      } | null)
    | ({
        relationTo: 'app-versions';
        value: number | AppVersion;
      } | null)
    | ({
        relationTo: 'app-listings';
        value: number | AppListing;
      } | null)
    | ({
        relationTo: 'app-metrics';
        value: number | AppMetric;
      } | null)
    | ({
        relationTo: 'connector-configs';
        value: number | ConnectorConfig;
      } | null)
    | ({
        relationTo: 'sync-tasks';
        value: number | SyncTask;
      } | null)
    | ({
        relationTo: 'task-attempts';
        value: number | TaskAttempt;
      } | null)
    | ({
        relationTo: 'collection-runs';
        value: number | CollectionRun;
      } | null)
    | ({
        relationTo: 'dead-letters';
        value: number | DeadLetter;
      } | null)
    | ({
        relationTo: 'ad-advertisers';
        value: number | AdAdvertiser;
      } | null)
    | ({
        relationTo: 'ads';
        value: number | Ad;
      } | null)
    | ({
        relationTo: 'ad-assets';
        value: number | AdAsset;
      } | null)
    | ({
        relationTo: 'ad-app-links';
        value: number | AdAppLink;
      } | null)
    | ({
        relationTo: 'payload-media';
        value: number | PayloadMedia;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'staff';
    value: number | Staff;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'staff';
    value: number | Staff;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff_select".
 */
export interface StaffSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  emailVerifiedAt?: T;
  passwordHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries_select".
 */
export interface CountriesSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  emoji?: T;
  isActiveIos?: T;
  isActiveAndroid?: T;
  iosLanguages?: T;
  androidLanguages?: T;
  priority?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-categories_select".
 */
export interface StoreCategoriesSelect<T extends boolean = true> {
  platform?: T;
  externalId?: T;
  name?: T;
  slug?: T;
  type?: T;
  parent?: T;
  priority?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publishers_select".
 */
export interface PublishersSelect<T extends boolean = true> {
  platform?: T;
  externalId?: T;
  name?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-apps_select".
 */
export interface CatalogAppsSelect<T extends boolean = true> {
  platform?: T;
  externalId?: T;
  publisher?: T;
  category?: T;
  displayName?: T;
  iconUrl?: T;
  originCountryCode?: T;
  supportedLocales?: T;
  originalReleaseDate?: T;
  isFree?: T;
  discoveredFrom?: T;
  discoveredAt?: T;
  lastSyncedAt?: T;
  isAvailable?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-versions_select".
 */
export interface AppVersionsSelect<T extends boolean = true> {
  app?: T;
  version?: T;
  releaseDate?: T;
  whatsNew?: T;
  fileSizeBytes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-listings_select".
 */
export interface AppListingsSelect<T extends boolean = true> {
  app?: T;
  version?: T;
  locale?: T;
  title?: T;
  subtitle?: T;
  promotionalText?: T;
  description?: T;
  whatsNew?: T;
  screenshots?: T;
  iconUrl?: T;
  videoUrl?: T;
  price?: T;
  currency?: T;
  fetchedAt?: T;
  checksum?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-metrics_select".
 */
export interface AppMetricsSelect<T extends boolean = true> {
  app?: T;
  version?: T;
  countryCode?: T;
  date?: T;
  rating?: T;
  ratingCount?: T;
  ratingBreakdown?: T;
  isAvailable?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "connector-configs_select".
 */
export interface ConnectorConfigsSelect<T extends boolean = true> {
  label?: T;
  source?: T;
  enabled?: T;
  transport?: T;
  capabilities?: T;
  countries?: T;
  requestsPerMinute?: T;
  concurrency?: T;
  health?: T;
  lastHealthCode?: T;
  lastSuccessAt?: T;
  lastFailureAt?: T;
  circuitOpenUntil?: T;
  secretStatus?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sync-tasks_select".
 */
export interface SyncTasksSelect<T extends boolean = true> {
  syncStatusId?: T;
  taskId?: T;
  kind?: T;
  payload?: T;
  status?: T;
  attemptCount?: T;
  failureReason?: T;
  errorMessage?: T;
  availableAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "task-attempts_select".
 */
export interface TaskAttemptsSelect<T extends boolean = true> {
  taskId?: T;
  attempt?: T;
  status?: T;
  source?: T;
  startedAt?: T;
  completedAt?: T;
  durationMs?: T;
  resultCount?: T;
  errorCode?: T;
  errorMessage?: T;
  rawR2Key?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collection-runs_select".
 */
export interface CollectionRunsSelect<T extends boolean = true> {
  targetId?: T;
  source?: T;
  reason?: T;
  status?: T;
  resultCount?: T;
  newAdCount?: T;
  linkedAppCount?: T;
  candidateCount?: T;
  errorMessage?: T;
  rawR2Key?: T;
  startedAt?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dead-letters_select".
 */
export interface DeadLettersSelect<T extends boolean = true> {
  taskId?: T;
  kind?: T;
  source?: T;
  status?: T;
  attemptCount?: T;
  errorCode?: T;
  errorMessage?: T;
  payload?: T;
  rawR2Key?: T;
  failedAt?: T;
  resolvedAt?: T;
  resolvedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-advertisers_select".
 */
export interface AdAdvertisersSelect<T extends boolean = true> {
  source?: T;
  sourceAdvertiserId?: T;
  name?: T;
  domain?: T;
  sourceUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ads_select".
 */
export interface AdsSelect<T extends boolean = true> {
  source?: T;
  sourceAdId?: T;
  advertiser?: T;
  sourceUrl?: T;
  status?: T;
  headline?: T;
  body?: T;
  callToAction?: T;
  landingUrl?: T;
  platforms?: T;
  languages?: T;
  startedAt?: T;
  endedAt?: T;
  impressionsMin?: T;
  impressionsMax?: T;
  reachMin?: T;
  reachMax?: T;
  spendMin?: T;
  spendMax?: T;
  currency?: T;
  firstCollectedAt?: T;
  lastCollectedAt?: T;
  rawR2Key?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-assets_select".
 */
export interface AdAssetsSelect<T extends boolean = true> {
  sha256?: T;
  r2Key?: T;
  mediaType?: T;
  mimeType?: T;
  byteSize?: T;
  width?: T;
  height?: T;
  durationMs?: T;
  originalUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-app-links_select".
 */
export interface AdAppLinksSelect<T extends boolean = true> {
  ad?: T;
  app?: T;
  candidateName?: T;
  confidence?: T;
  matchReason?: T;
  verified?: T;
  verifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-media_select".
 */
export interface PayloadMediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  actor?: T;
  action?: T;
  entityType?: T;
  entityId?: T;
  metadata?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}