import { readFileSync, existsSync, readdirSync, statSync } from 'node:fs'
import { resolve, extname } from 'node:path'
import { describe, expect, it } from 'vitest'

const root = resolve(import.meta.dirname, '..')
type OpenApiOperation = { operationId?: string; security?: unknown[]; parameters?: Array<{ name: string; in: string; required: boolean }> }
const openapi = JSON.parse(readFileSync(resolve(root, 'packages/contracts/openapi.json'), 'utf8')) as { paths: Record<string, Record<string, OpenApiOperation>> }

describe('public contract', () => {
  it('publishes all 45 compatible path templates', () => expect(Object.keys(openapi.paths)).toHaveLength(45))
  it.each(['/auth/register', '/apps/{platform}/{externalId}', '/charts', '/publishers/{platform}/{externalId}/import'])('contains %s', (path) => expect(openapi.paths[path]).toBeDefined())
  it('declares secure browser cookie and bearer schemes', () => {
    const text = JSON.stringify(openapi)
    expect(text).toContain('__Host-openapps-session')
    expect(text).toContain('bearerAuth')
  })
  it('assigns a unique operationId and every required path parameter to all 53 operations', () => {
    const operations = Object.entries(openapi.paths).flatMap(([path, methods]) => Object.values(methods).map((operation) => ({ path, operation })))
    const ids = operations.map(({ operation }) => operation.operationId)
    expect(operations).toHaveLength(53)
    expect(ids.every(Boolean)).toBe(true)
    expect(new Set(ids).size).toBe(53)
    for (const { path, operation } of operations) {
      const expected = [...path.matchAll(/\{([^}]+)\}/g)].map((match) => match[1])
      const actual = (operation.parameters ?? []).filter((parameter) => parameter.in === 'path' && parameter.required).map((parameter) => parameter.name)
      expect(actual).toEqual(expected)
    }
  })
  it('leaves only registration and login public', () => {
    expect(openapi.paths['/auth/register']!.post!.security).toEqual([])
    expect(openapi.paths['/auth/login']!.post!.security).toEqual([])
    expect(openapi.paths['/auth/me']!.get!.security).not.toEqual([])
    expect(openapi.paths['/auth/logout']!.post!.security).not.toEqual([])
  })
  it('keeps the Orval React client regenerated for every public operation', () => {
    const generated = readFileSync(resolve(root, 'web/src/api/contract/openapps.ts'), 'utf8')
    const operationIds = Object.values(openapi.paths).flatMap((methods) => Object.values(methods).map((operation) => operation.operationId!))
    expect(generated).toContain('Generated by orval')
    for (const operationId of operationIds) expect(generated).toMatch(new RegExp(`export const ${operationId} =`))
    const noContentOperations = Object.values(openapi.paths).flatMap((methods) => Object.values(methods)).filter((operation) => '204' in ((operation as unknown as { responses: Record<string, unknown> }).responses ?? {}))
    expect(generated.match(/orvalMutator<void>/g)).toHaveLength(noContentOperations.length)
  })
})

describe('MCP surface', () => {
  const remote = readFileSync(resolve(root, 'workers/web/src/mcp.ts'), 'utf8')
  const stdioFiles = readdirSync(resolve(root, 'mcp/src/tools')).filter((file) => file.endsWith('.ts'))
  const stdio = stdioFiles.map((file) => readFileSync(resolve(root, 'mcp/src/tools', file), 'utf8')).join('\n')
  const names = [...remote.matchAll(/name: '([^']+)'/g)].map((match) => match[1]).filter((name) => name.includes('_'))
  it('exposes exactly 29 unique remote tools', () => { expect(names).toHaveLength(29); expect(new Set(names).size).toBe(29) })
  it('keeps every stdio tool on the remote server', () => {
    const localNames = [...stdio.matchAll(/registerTool\(\s*['"]([^'"]+)/g)].map((match) => match[1])
    expect(localNames).toHaveLength(29)
    expect(new Set(names)).toEqual(new Set(localNames))
  })
  it('keeps exactly four write tools', () => expect((remote.match(/write: true/g) ?? [])).toHaveLength(4))
})

describe('native runtime boundary', () => {
  it.each(['server', 'scraper-android', 'scraper-ios', 'docker-compose.yml', 'docker-compose.production.yml'])('removes %s', (path) => expect(existsSync(resolve(root, path))).toBe(false))
  it('contains no tracked legacy runtime source', () => {
    const excluded = new Set(['node_modules', '.git', 'dist'])
    const found: string[] = []
    const walk = (dir: string) => { for (const name of readdirSync(dir)) { if (excluded.has(name)) continue; const path = resolve(dir, name); if (statSync(path).isDirectory()) walk(path); else if (['.php', '.py'].includes(extname(path)) || name === 'Dockerfile') found.push(path) } }
    walk(root)
    expect(found).toEqual([])
  })
})
