/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { AppPlatform } from './appPlatform';

export interface App {
  id: number;
  name: string;
  platform: AppPlatform;
  external_id: string;
  icon_url: string | null;
  rating: number | null;
  rating_count: number | null;
  version: string | null;
  is_available: boolean;
  is_tracked: boolean;
  [key: string]: unknown;
}
