/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { AppChanges422Errors } from './appChanges422Errors';

export type AppChanges422 = {
  message: string;
  errors?: AppChanges422Errors;
};
