/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { AppKeywordsOrder } from './appKeywordsOrder';
import type { AppKeywordsSort } from './appKeywordsSort';

export type AppKeywordsParams = {
locale?: string;
/**
 * @minimum 1
 * @maximum 4
 */
ngram?: number;
/**
 * @minimum 1
 */
version_id?: number;
/**
 * @maxLength 100
 */
search?: string;
sort?: AppKeywordsSort;
order?: AppKeywordsOrder;
/**
 * @minimum 1
 * @maximum 500
 */
per_page?: number;
/**
 * @minimum 1
 */
page?: number;
};
