/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { AppKeywords401Errors } from './appKeywords401Errors';

export type AppKeywords401 = {
  message: string;
  errors?: AppKeywords401Errors;
};
