/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { AppListing422Errors } from './appListing422Errors';

export type AppListing422 = {
  message: string;
  errors?: AppListing422Errors;
};
