/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */

export type CompareKeywordsParams = {
/**
 * @minItems 1
 * @maxItems 5
 * @items.minimum 1
 */
'app_ids[]': number[];
locale?: string;
/**
 * @minimum 1
 * @maximum 4
 */
ngram?: number;
};
