/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { CompetitorChangesPlatform } from './competitorChangesPlatform';

export type CompetitorChangesParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
per_page?: number;
field?: string;
platform?: CompetitorChangesPlatform;
/**
 * @maxLength 100
 */
search?: string;
/**
 * @minimum 1
 */
app_id?: number;
folder_id?: string;
};
