/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */

export type CompetitorChangesPlatform = typeof CompetitorChangesPlatform[keyof typeof CompetitorChangesPlatform];


export const CompetitorChangesPlatform = {
  ios: 'ios',
  android: 'android',
} as const;
