/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { CreateApiToken422Errors } from './createApiToken422Errors';

export type CreateApiToken422 = {
  message: string;
  errors?: CreateApiToken422Errors;
};
