/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { DestroyFolder401Errors } from './destroyFolder401Errors';

export type DestroyFolder401 = {
  message: string;
  errors?: DestroyFolder401Errors;
};
