/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { DestroyFolder422Errors } from './destroyFolder422Errors';

export type DestroyFolder422 = {
  message: string;
  errors?: DestroyFolder422Errors;
};
