/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ExploreScreenshotsPlatform } from './exploreScreenshotsPlatform';

export type ExploreScreenshotsParams = {
platform?: ExploreScreenshotsPlatform;
/**
 * @minimum 1
 */
category_id?: number;
search?: string;
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
per_page?: number;
};
