/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */

export type GetChartsCollection = typeof GetChartsCollection[keyof typeof GetChartsCollection];


export const GetChartsCollection = {
  top_free: 'top_free',
  top_paid: 'top_paid',
  top_grossing: 'top_grossing',
} as const;
