/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { GetChartsCollection } from './getChartsCollection';
import type { GetChartsPlatform } from './getChartsPlatform';

export type GetChartsParams = {
platform: GetChartsPlatform;
collection: GetChartsCollection;
/**
 * @minLength 2
 * @maxLength 2
 */
country_code?: string;
/**
 * @minimum 1
 */
category_id?: number;
};
