/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { GetCharts422Errors } from './getCharts422Errors';

export type GetCharts422 = {
  message: string;
  errors?: GetCharts422Errors;
};
