/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { GetRatingHistory401Errors } from './getRatingHistory401Errors';

export type GetRatingHistory401 = {
  message: string;
  errors?: GetRatingHistory401Errors;
};
