/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ImportPublisherApps401Errors } from './importPublisherApps401Errors';

export type ImportPublisherApps401 = {
  message: string;
  errors?: ImportPublisherApps401Errors;
};
