/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ListCreatives200DataItemProvenanceSource } from './listCreatives200DataItemProvenanceSource';

export type ListCreatives200DataItemProvenance = {
  source: ListCreatives200DataItemProvenanceSource;
  collected_at: string;
  raw_archived: boolean;
};
