/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ListAppCreatives200DataItemAdvertiser } from './listAppCreatives200DataItemAdvertiser';
import type { ListAppCreatives200DataItemPreview } from './listAppCreatives200DataItemPreview';
import type { ListAppCreatives200DataItemProvenance } from './listAppCreatives200DataItemProvenance';
import type { ListAppCreatives200DataItemSource } from './listAppCreatives200DataItemSource';
import type { ListAppCreatives200DataItemStatus } from './listAppCreatives200DataItemStatus';

export type ListAppCreatives200DataItem = {
  id: number;
  source: ListAppCreatives200DataItemSource;
  source_ad_id: string;
  source_url: string | null;
  status: ListAppCreatives200DataItemStatus;
  advertiser: ListAppCreatives200DataItemAdvertiser;
  headline: string | null;
  body: string | null;
  call_to_action: string | null;
  landing_url: string | null;
  platforms: string[];
  languages: string[];
  started_at: string | null;
  ended_at: string | null;
  preview: ListAppCreatives200DataItemPreview;
  variants_count: number;
  apps_count: number;
  provenance: ListAppCreatives200DataItemProvenance;
  first_collected_at: string;
  last_collected_at: string;
  [key: string]: unknown;
};
