/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ListAdvertiserCreatives200DataItemAdvertiser } from './listAdvertiserCreatives200DataItemAdvertiser';
import type { ListAdvertiserCreatives200DataItemPreview } from './listAdvertiserCreatives200DataItemPreview';
import type { ListAdvertiserCreatives200DataItemProvenance } from './listAdvertiserCreatives200DataItemProvenance';
import type { ListAdvertiserCreatives200DataItemSource } from './listAdvertiserCreatives200DataItemSource';
import type { ListAdvertiserCreatives200DataItemStatus } from './listAdvertiserCreatives200DataItemStatus';

export type ListAdvertiserCreatives200DataItem = {
  id: number;
  source: ListAdvertiserCreatives200DataItemSource;
  source_ad_id: string;
  source_url: string | null;
  status: ListAdvertiserCreatives200DataItemStatus;
  advertiser: ListAdvertiserCreatives200DataItemAdvertiser;
  headline: string | null;
  body: string | null;
  call_to_action: string | null;
  landing_url: string | null;
  platforms: string[];
  languages: string[];
  started_at: string | null;
  ended_at: string | null;
  preview: ListAdvertiserCreatives200DataItemPreview;
  variants_count: number;
  apps_count: number;
  provenance: ListAdvertiserCreatives200DataItemProvenance;
  first_collected_at: string;
  last_collected_at: string;
  [key: string]: unknown;
};
