/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ListApps200ItemPlatform } from './listApps200ItemPlatform';

export type ListApps200Item = {
  id: number;
  name: string;
  platform: ListApps200ItemPlatform;
  external_id: string;
  icon_url: string | null;
  rating: number | null;
  rating_count: number | null;
  version: string | null;
  is_available: boolean;
  is_tracked: boolean;
  [key: string]: unknown;
};
