/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ListCreatives401Errors } from './listCreatives401Errors';

export type ListCreatives401 = {
  message: string;
  errors?: ListCreatives401Errors;
};
