/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ListCreativesFormat } from './listCreativesFormat';
import type { ListCreativesSource } from './listCreativesSource';
import type { ListCreativesStatus } from './listCreativesStatus';

export type ListCreativesParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
per_page?: number;
/**
 * @maxLength 100
 */
search?: string;
source?: ListCreativesSource;
app?: string;
/**
 * @minimum 1
 */
app_id?: number;
/**
 * @minimum 1
 */
advertiser_id?: number;
/**
 * @minimum 1
 */
publisher_id?: number;
/**
 * @minLength 2
 * @maxLength 2
 */
country?: string;
format?: ListCreativesFormat;
status?: ListCreativesStatus;
date_from?: string;
date_to?: string;
};
