/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */

export type ListAppCreatives200DataItemStatus = typeof ListAppCreatives200DataItemStatus[keyof typeof ListAppCreatives200DataItemStatus];


export const ListAppCreatives200DataItemStatus = {
  active: 'active',
  inactive: 'inactive',
  removed: 'removed',
  unknown: 'unknown',
} as const;
