/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ListAllCompetitors422Errors } from './listAllCompetitors422Errors';

export type ListAllCompetitors422 = {
  message: string;
  errors?: ListAllCompetitors422Errors;
};
