/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */

export type ListAppCreatives200DataItemPreviewType = typeof ListAppCreatives200DataItemPreviewType[keyof typeof ListAppCreatives200DataItemPreviewType];


export const ListAppCreatives200DataItemPreviewType = {
  image: 'image',
  video: 'video',
  thumbnail: 'thumbnail',
} as const;
