/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ListAdvertiserCreatives422Errors } from './listAdvertiserCreatives422Errors';

export type ListAdvertiserCreatives422 = {
  message: string;
  errors?: ListAdvertiserCreatives422Errors;
};
