/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ListAppCreatives200DataItemPreviewType } from './listAppCreatives200DataItemPreviewType';

export type ListAppCreatives200DataItemPreview = {
  url: string;
  type: ListAppCreatives200DataItemPreviewType;
  mime_type: string;
} | null;
