/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */

export type ListAdvertiserCreatives200DataItemSource = typeof ListAdvertiserCreatives200DataItemSource[keyof typeof ListAdvertiserCreatives200DataItemSource];


export const ListAdvertiserCreatives200DataItemSource = {
  meta: 'meta',
  google: 'google',
  tiktok: 'tiktok',
} as const;
