/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ListCreatives200Coverage } from './listCreatives200Coverage';
import type { ListCreatives200DataItem } from './listCreatives200DataItem';
import type { ListCreatives200Links } from './listCreatives200Links';
import type { ListCreatives200Meta } from './listCreatives200Meta';

export type ListCreatives200 = {
  data: ListCreatives200DataItem[];
  links: ListCreatives200Links;
  meta: ListCreatives200Meta;
  coverage: ListCreatives200Coverage;
};
