/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */

export type ListCreativesFormat = typeof ListCreativesFormat[keyof typeof ListCreativesFormat];


export const ListCreativesFormat = {
  image: 'image',
  video: 'video',
  carousel: 'carousel',
  text: 'text',
  unknown: 'unknown',
} as const;
