/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ListAdvertiserCreatives200Coverage } from './listAdvertiserCreatives200Coverage';
import type { ListAdvertiserCreatives200DataItem } from './listAdvertiserCreatives200DataItem';
import type { ListAdvertiserCreatives200Links } from './listAdvertiserCreatives200Links';
import type { ListAdvertiserCreatives200Meta } from './listAdvertiserCreatives200Meta';

export type ListAdvertiserCreatives200 = {
  data: ListAdvertiserCreatives200DataItem[];
  links: ListAdvertiserCreatives200Links;
  meta: ListAdvertiserCreatives200Meta;
  coverage: ListAdvertiserCreatives200Coverage;
};
