/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */

export type ListCreatives200DataItemSource = typeof ListCreatives200DataItemSource[keyof typeof ListCreatives200DataItemSource];


export const ListCreatives200DataItemSource = {
  meta: 'meta',
  google: 'google',
  tiktok: 'tiktok',
} as const;
