/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ListCreatives422Errors } from './listCreatives422Errors';

export type ListCreatives422 = {
  message: string;
  errors?: ListCreatives422Errors;
};
