/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ListStoreCategoriesPlatform } from './listStoreCategoriesPlatform';
import type { ListStoreCategoriesType } from './listStoreCategoriesType';

export type ListStoreCategoriesParams = {
platform?: ListStoreCategoriesPlatform;
type?: ListStoreCategoriesType;
};
