/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ListPublishers422Errors } from './listPublishers422Errors';

export type ListPublishers422 = {
  message: string;
  errors?: ListPublishers422Errors;
};
