/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */

export type ListCreatives200Meta = {
  current_page: number;
  last_page: number;
  per_page: number;
  total: number;
};
