/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */

export type ListAppCreatives200DataItemProvenanceSource = typeof ListAppCreatives200DataItemProvenanceSource[keyof typeof ListAppCreatives200DataItemProvenanceSource];


export const ListAppCreatives200DataItemProvenanceSource = {
  meta: 'meta',
  google: 'google',
  tiktok: 'tiktok',
} as const;
