/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */

export type ListCreatives200DataItemStatus = typeof ListCreatives200DataItemStatus[keyof typeof ListCreatives200DataItemStatus];


export const ListCreatives200DataItemStatus = {
  active: 'active',
  inactive: 'inactive',
  removed: 'removed',
  unknown: 'unknown',
} as const;
