/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ListApiTokens422Errors } from './listApiTokens422Errors';

export type ListApiTokens422 = {
  message: string;
  errors?: ListApiTokens422Errors;
};
