/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ListAdvertiserCreativesFormat } from './listAdvertiserCreativesFormat';
import type { ListAdvertiserCreativesSource } from './listAdvertiserCreativesSource';

export type ListAdvertiserCreativesParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
per_page?: number;
source?: ListAdvertiserCreativesSource;
/**
 * @minLength 2
 * @maxLength 2
 */
country?: string;
format?: ListAdvertiserCreativesFormat;
};
