/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */

export type ListCreativesStatus = typeof ListCreativesStatus[keyof typeof ListCreativesStatus];


export const ListCreativesStatus = {
  active: 'active',
  inactive: 'inactive',
  removed: 'removed',
  unknown: 'unknown',
} as const;
