/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */

export type ListAdvertiserCreatives200DataItemPreviewType = typeof ListAdvertiserCreatives200DataItemPreviewType[keyof typeof ListAdvertiserCreatives200DataItemPreviewType];


export const ListAdvertiserCreatives200DataItemPreviewType = {
  image: 'image',
  video: 'video',
  thumbnail: 'thumbnail',
} as const;
