/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ListAppCreatives401Errors } from './listAppCreatives401Errors';

export type ListAppCreatives401 = {
  message: string;
  errors?: ListAppCreatives401Errors;
};
