/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ListAdvertiserCreatives200DataItemProvenanceSource } from './listAdvertiserCreatives200DataItemProvenanceSource';

export type ListAdvertiserCreatives200DataItemProvenance = {
  source: ListAdvertiserCreatives200DataItemProvenanceSource;
  collected_at: string;
  raw_archived: boolean;
};
