/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ListCompetitors422Errors } from './listCompetitors422Errors';

export type ListCompetitors422 = {
  message: string;
  errors?: ListCompetitors422Errors;
};
