/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ListCreatives200DataItemAdvertiser } from './listCreatives200DataItemAdvertiser';
import type { ListCreatives200DataItemPreview } from './listCreatives200DataItemPreview';
import type { ListCreatives200DataItemProvenance } from './listCreatives200DataItemProvenance';
import type { ListCreatives200DataItemSource } from './listCreatives200DataItemSource';
import type { ListCreatives200DataItemStatus } from './listCreatives200DataItemStatus';

export type ListCreatives200DataItem = {
  id: number;
  source: ListCreatives200DataItemSource;
  source_ad_id: string;
  source_url: string | null;
  status: ListCreatives200DataItemStatus;
  advertiser: ListCreatives200DataItemAdvertiser;
  headline: string | null;
  body: string | null;
  call_to_action: string | null;
  landing_url: string | null;
  platforms: string[];
  languages: string[];
  started_at: string | null;
  ended_at: string | null;
  preview: ListCreatives200DataItemPreview;
  variants_count: number;
  apps_count: number;
  provenance: ListCreatives200DataItemProvenance;
  first_collected_at: string;
  last_collected_at: string;
  [key: string]: unknown;
};
