/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ListAppCreatives422Errors } from './listAppCreatives422Errors';

export type ListAppCreatives422 = {
  message: string;
  errors?: ListAppCreatives422Errors;
};
