/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ListAppCreativesFormat } from './listAppCreativesFormat';
import type { ListAppCreativesSource } from './listAppCreativesSource';

export type ListAppCreativesParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
per_page?: number;
source?: ListAppCreativesSource;
/**
 * @minLength 2
 * @maxLength 2
 */
country?: string;
format?: ListAppCreativesFormat;
};
