/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ListAppCreatives200Coverage } from './listAppCreatives200Coverage';
import type { ListAppCreatives200DataItem } from './listAppCreatives200DataItem';
import type { ListAppCreatives200Links } from './listAppCreatives200Links';
import type { ListAppCreatives200Meta } from './listAppCreatives200Meta';

export type ListAppCreatives200 = {
  data: ListAppCreatives200DataItem[];
  links: ListAppCreatives200Links;
  meta: ListAppCreatives200Meta;
  coverage: ListAppCreatives200Coverage;
};
