/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ListAdvertiserCreatives200DataItemPreviewType } from './listAdvertiserCreatives200DataItemPreviewType';

export type ListAdvertiserCreatives200DataItemPreview = {
  url: string;
  type: ListAdvertiserCreatives200DataItemPreviewType;
  mime_type: string;
} | null;
