/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ListCompetitors401Errors } from './listCompetitors401Errors';

export type ListCompetitors401 = {
  message: string;
  errors?: ListCompetitors401Errors;
};
