/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ListAppsPlatform } from './listAppsPlatform';

export type ListAppsParams = {
platform?: ListAppsPlatform;
/**
 * @maxLength 100
 */
search?: string;
folder_id?: string;
};
