/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */

export type ListCreatives200DataItemProvenanceSource = typeof ListCreatives200DataItemProvenanceSource[keyof typeof ListCreatives200DataItemProvenanceSource];


export const ListCreatives200DataItemProvenanceSource = {
  meta: 'meta',
  google: 'google',
  tiktok: 'tiktok',
} as const;
