/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ListFolders401Errors } from './listFolders401Errors';

export type ListFolders401 = {
  message: string;
  errors?: ListFolders401Errors;
};
