/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { MoveAppToFolder422Errors } from './moveAppToFolder422Errors';

export type MoveAppToFolder422 = {
  message: string;
  errors?: MoveAppToFolder422Errors;
};
