/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { PublisherStoreApps401Errors } from './publisherStoreApps401Errors';

export type PublisherStoreApps401 = {
  message: string;
  errors?: PublisherStoreApps401Errors;
};
