/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { Register422Errors } from './register422Errors';

export type Register422 = {
  message: string;
  errors?: Register422Errors;
};
