/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { Register401Errors } from './register401Errors';

export type Register401 = {
  message: string;
  errors?: Register401Errors;
};
