/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { SearchApps401Errors } from './searchApps401Errors';

export type SearchApps401 = {
  message: string;
  errors?: SearchApps401Errors;
};
