/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { SearchPublishersPlatform } from './searchPublishersPlatform';

export type SearchPublishersParams = {
/**
 * @minLength 2
 */
term: string;
platform: SearchPublishersPlatform;
/**
 * @minLength 2
 * @maxLength 2
 */
country_code?: string;
};
