/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ShowPublisher401Errors } from './showPublisher401Errors';

export type ShowPublisher401 = {
  message: string;
  errors?: ShowPublisher401Errors;
};
