/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ShowApp401Errors } from './showApp401Errors';

export type ShowApp401 = {
  message: string;
  errors?: ShowApp401Errors;
};
