/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ShowCreative401Errors } from './showCreative401Errors';

export type ShowCreative401 = {
  message: string;
  errors?: ShowCreative401Errors;
};
