/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ShowCreative200PreviewType } from './showCreative200PreviewType';

export type ShowCreative200Preview = {
  url: string;
  type: ShowCreative200PreviewType;
  mime_type: string;
} | null;
