/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */

export type ShowCreative200Advertiser = {
  id: number;
  name: string;
  domain: string | null;
} | null;
