/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */

export type ShowCreative200PreviewType = typeof ShowCreative200PreviewType[keyof typeof ShowCreative200PreviewType];


export const ShowCreative200PreviewType = {
  image: 'image',
  video: 'video',
  thumbnail: 'thumbnail',
} as const;
