/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ShowCreative200Advertiser } from './showCreative200Advertiser';
import type { ShowCreative200Preview } from './showCreative200Preview';
import type { ShowCreative200Provenance } from './showCreative200Provenance';
import type { ShowCreative200Source } from './showCreative200Source';
import type { ShowCreative200Status } from './showCreative200Status';

export type ShowCreative200 = {
  id: number;
  source: ShowCreative200Source;
  source_ad_id: string;
  source_url: string | null;
  status: ShowCreative200Status;
  advertiser: ShowCreative200Advertiser;
  headline: string | null;
  body: string | null;
  call_to_action: string | null;
  landing_url: string | null;
  platforms: string[];
  languages: string[];
  started_at: string | null;
  ended_at: string | null;
  preview: ShowCreative200Preview;
  variants_count: number;
  apps_count: number;
  provenance: ShowCreative200Provenance;
  first_collected_at: string;
  last_collected_at: string;
  [key: string]: unknown;
};
