/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ShowApp200Platform } from './showApp200Platform';

export type ShowApp200 = {
  id: number;
  name: string;
  platform: ShowApp200Platform;
  external_id: string;
  icon_url: string | null;
  rating: number | null;
  rating_count: number | null;
  version: string | null;
  is_available: boolean;
  is_tracked: boolean;
  [key: string]: unknown;
};
