/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { ShowCreative200ProvenanceSource } from './showCreative200ProvenanceSource';

export type ShowCreative200Provenance = {
  source: ShowCreative200ProvenanceSource;
  collected_at: string;
  raw_archived: boolean;
};
