/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { StoreFolder401Errors } from './storeFolder401Errors';

export type StoreFolder401 = {
  message: string;
  errors?: StoreFolder401Errors;
};
