/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { StoreFolder422Errors } from './storeFolder422Errors';

export type StoreFolder422 = {
  message: string;
  errors?: StoreFolder422Errors;
};
