/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { StoreApp401Errors } from './storeApp401Errors';

export type StoreApp401 = {
  message: string;
  errors?: StoreApp401Errors;
};
