/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { StoreCompetitor401Errors } from './storeCompetitor401Errors';

export type StoreCompetitor401 = {
  message: string;
  errors?: StoreCompetitor401Errors;
};
