/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */

export type StoreAppBodyPlatform = typeof StoreAppBodyPlatform[keyof typeof StoreAppBodyPlatform];


export const StoreAppBodyPlatform = {
  ios: 'ios',
  android: 'android',
} as const;
