/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { StoreApp422Errors } from './storeApp422Errors';

export type StoreApp422 = {
  message: string;
  errors?: StoreApp422Errors;
};
