/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { StoreCompetitor422Errors } from './storeCompetitor422Errors';

export type StoreCompetitor422 = {
  message: string;
  errors?: StoreCompetitor422Errors;
};
