/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { StoreCompetitorBodyCompetitorPlatform } from './storeCompetitorBodyCompetitorPlatform';
import type { StoreCompetitorBodyRelationship } from './storeCompetitorBodyRelationship';

export type StoreCompetitorBody = {
  competitor_app_id?: number;
  competitor_platform?: StoreCompetitorBodyCompetitorPlatform;
  competitor_external_id?: string;
  relationship?: StoreCompetitorBodyRelationship;
};
