/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */

export type StoreFolder201 = {
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  id: number;
  name: string;
  color: string;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  sort_order: number;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  apps_count: number;
  created_at: string;
  updated_at: string;
};
