/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { SyncAppCreatives202Status } from './syncAppCreatives202Status';

export type SyncAppCreatives202 = {
  status: SyncAppCreatives202Status;
  target_id: number;
};
