/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */

export type SyncAppCreatives202Status = typeof SyncAppCreatives202Status[keyof typeof SyncAppCreatives202Status];


export const SyncAppCreatives202Status = {
  queued: 'queued',
  running: 'running',
} as const;
