/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { SyncApp422Errors } from './syncApp422Errors';

export type SyncApp422 = {
  message: string;
  errors?: SyncApp422Errors;
};
