/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { TrackApp401Errors } from './trackApp401Errors';

export type TrackApp401 = {
  message: string;
  errors?: TrackApp401Errors;
};
