/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { UntrackApp401Errors } from './untrackApp401Errors';

export type UntrackApp401 = {
  message: string;
  errors?: UntrackApp401Errors;
};
