/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { UpdatePassword422Errors } from './updatePassword422Errors';

export type UpdatePassword422 = {
  message: string;
  errors?: UpdatePassword422Errors;
};
