/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { UpdateProfile422Errors } from './updateProfile422Errors';

export type UpdateProfile422 = {
  message: string;
  errors?: UpdateProfile422Errors;
};
