/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */
import type { UpdatePassword401Errors } from './updatePassword401Errors';

export type UpdatePassword401 = {
  message: string;
  errors?: UpdatePassword401Errors;
};
