/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Cloudflare-native App Store and Google Play intelligence API.
 * OpenAPI spec version: 2.0.0
 */

export type UpdateFolderBodyColor = typeof UpdateFolderBodyColor[keyof typeof UpdateFolderBodyColor];


export const UpdateFolderBodyColor = {
  slate: 'slate',
  red: 'red',
  orange: 'orange',
  amber: 'amber',
  yellow: 'yellow',
  lime: 'lime',
  green: 'green',
  emerald: 'emerald',
  teal: 'teal',
  cyan: 'cyan',
  sky: 'sky',
  blue: 'blue',
  indigo: 'indigo',
  violet: 'violet',
  purple: 'purple',
  fuchsia: 'fuchsia',
  pink: 'pink',
  rose: 'rose',
} as const;
