/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  FolderResource,
  StoreFolderRequest,
  UpdateFolderRequest
} from '../../models';

import { orvalMutator } from '../../../lib/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List folders for the authenticated user
 */
export const listFolders = (

 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<FolderResource[]>(
      {url: `/folders`, method: 'GET', signal
    },
      options);
    }




export const getListFoldersQueryKey = () => {
    return [
    `/folders`
    ] as const;
    }


export const getListFoldersQueryOptions = <TData = Awaited<ReturnType<typeof listFolders>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFolders>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListFoldersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listFolders>>> = ({ signal }) => listFolders(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listFolders>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListFoldersQueryResult = NonNullable<Awaited<ReturnType<typeof listFolders>>>
export type ListFoldersQueryError = unknown


export function useListFolders<TData = Awaited<ReturnType<typeof listFolders>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFolders>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFolders>>,
          TError,
          Awaited<ReturnType<typeof listFolders>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFolders<TData = Awaited<ReturnType<typeof listFolders>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFolders>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFolders>>,
          TError,
          Awaited<ReturnType<typeof listFolders>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFolders<TData = Awaited<ReturnType<typeof listFolders>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFolders>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List folders for the authenticated user
 */

export function useListFolders<TData = Awaited<ReturnType<typeof listFolders>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFolders>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListFoldersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create a folder
 */
export const storeFolder = (
    storeFolderRequest: StoreFolderRequest,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<FolderResource>(
      {url: `/folders`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: storeFolderRequest, signal
    },
      options);
    }



export const getStoreFolderMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof storeFolder>>, TError,{data: StoreFolderRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof storeFolder>>, TError,{data: StoreFolderRequest}, TContext> => {

const mutationKey = ['storeFolder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof storeFolder>>, {data: StoreFolderRequest}> = (props) => {
          const {data} = props ?? {};

          return  storeFolder(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type StoreFolderMutationResult = NonNullable<Awaited<ReturnType<typeof storeFolder>>>
    export type StoreFolderMutationBody = StoreFolderRequest
    export type StoreFolderMutationError = void

    /**
 * @summary Create a folder
 */
export const useStoreFolder = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof storeFolder>>, TError,{data: StoreFolderRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof storeFolder>>,
        TError,
        {data: StoreFolderRequest},
        TContext
      > => {
      return useMutation(getStoreFolderMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete a folder (tracked apps stay, folder_id becomes NULL)
 */
export const destroyFolder = (
    folder: number,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<void>(
      {url: `/folders/${folder}`, method: 'DELETE', signal
    },
      options);
    }



export const getDestroyFolderMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof destroyFolder>>, TError,{folder: number}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof destroyFolder>>, TError,{folder: number}, TContext> => {

const mutationKey = ['destroyFolder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof destroyFolder>>, {folder: number}> = (props) => {
          const {folder} = props ?? {};

          return  destroyFolder(folder,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DestroyFolderMutationResult = NonNullable<Awaited<ReturnType<typeof destroyFolder>>>

    export type DestroyFolderMutationError = void

    /**
 * @summary Delete a folder (tracked apps stay, folder_id becomes NULL)
 */
export const useDestroyFolder = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof destroyFolder>>, TError,{folder: number}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof destroyFolder>>,
        TError,
        {folder: number},
        TContext
      > => {
      return useMutation(getDestroyFolderMutationOptions(options), queryClient);
    }
    /**
 * @summary Update a folder
 */
export const updateFolder = (
    folder: number,
    updateFolderRequest: UpdateFolderRequest,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<FolderResource>(
      {url: `/folders/${folder}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateFolderRequest, signal
    },
      options);
    }



export const getUpdateFolderMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFolder>>, TError,{folder: number;data: UpdateFolderRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof updateFolder>>, TError,{folder: number;data: UpdateFolderRequest}, TContext> => {

const mutationKey = ['updateFolder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateFolder>>, {folder: number;data: UpdateFolderRequest}> = (props) => {
          const {folder,data} = props ?? {};

          return  updateFolder(folder,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateFolderMutationResult = NonNullable<Awaited<ReturnType<typeof updateFolder>>>
    export type UpdateFolderMutationBody = UpdateFolderRequest
    export type UpdateFolderMutationError = void

    /**
 * @summary Update a folder
 */
export const useUpdateFolder = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFolder>>, TError,{folder: number;data: UpdateFolderRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateFolder>>,
        TError,
        {folder: number;data: UpdateFolderRequest},
        TContext
      > => {
      return useMutation(getUpdateFolderMutationOptions(options), queryClient);
    }
