import type { AuthContext, Database, JobMessage } from '@openapps/core'

// The binding surface itself is generated by `wrangler types`. This refinement
// only carries the queue payload type that Wrangler cannot infer from JSON.
export type Env = Cloudflare.Env & {
  SYNC_TRACKED_IOS: Queue<JobMessage>
  SYNC_TRACKED_ANDROID: Queue<JobMessage>
  SYNC_ON_DEMAND_IOS: Queue<JobMessage>
  SYNC_ON_DEMAND_ANDROID: Queue<JobMessage>
  CHARTS_IOS: Queue<JobMessage>
  CHARTS_ANDROID: Queue<JobMessage>
  RECONCILE: Queue<JobMessage>
}

export type Variables = { auth: AuthContext; db: Database }
