/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: c365e3fd0cdb0d6ecdde2dba55e53387)
interface __BaseEnv_Env {
	OAUTH_KV: KVNamespace;
	ARTIFACTS: R2Bucket;
	CREATIVES: R2Bucket;
	DB: D1Database;
	SYNC_TRACKED_IOS: Queue;
	SYNC_TRACKED_ANDROID: Queue;
	SYNC_ON_DEMAND_IOS: Queue;
	SYNC_ON_DEMAND_ANDROID: Queue;
	CHARTS_IOS: Queue;
	CHARTS_ANDROID: Queue;
	RECONCILE: Queue;
	CREATIVE_DISCOVERY: Queue;
	AUTH_RATE_LIMITER: RateLimit;
	API_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	APP_NAME: "OpenApps";
	APP_URL: "https://apps.mbza.dev";
	ENVIRONMENT: "production";
	TRACKED_APP_REFRESH_HOURS: "24";
	CREATIVES_ENABLED: "true";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_NAME" | "APP_URL" | "ENVIRONMENT" | "TRACKED_APP_REFRESH_HOURS" | "CREATIVES_ENABLED">> {}
}
