/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: 8f50d667f6e3637d4b93893ed92221e2)
interface __BaseEnv_Env {
	ARTIFACTS: R2Bucket;
	CREATIVES: R2Bucket;
	DB: D1Database;
	SYNC_TRACKED_IOS: Queue;
	SYNC_TRACKED_ANDROID: Queue;
	SYNC_ON_DEMAND_IOS: Queue;
	SYNC_ON_DEMAND_ANDROID: Queue;
	CHARTS_IOS: Queue;
	CHARTS_ANDROID: Queue;
	RECONCILE: Queue;
	CREATIVE_DISCOVERY: Queue;
	CREATIVE_MEDIA: Queue;
	BROWSER: BrowserRun;
	ENVIRONMENT: "production";
	CREATIVES_ENABLED: "true";
	CREATIVE_SOURCES: "meta,google,tiktok";
	CREATIVE_BACKFILL_LIMIT: "10";
	META_GRAPH_API_VERSION: "v23.0";
	STORE_RATE_LIMITER: DurableObjectNamespace<import("./index").StoreRateLimiter>;
	CREATIVE_SOURCE_LIMITER: DurableObjectNamespace<import("./index").CreativeSourceLimiter>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "StoreRateLimiter" | "CreativeSourceLimiter";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "CREATIVES_ENABLED" | "CREATIVE_SOURCES" | "CREATIVE_BACKFILL_LIMIT" | "META_GRAPH_API_VERSION">> {}
}
