/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 15ab78b7618120d925258959d5be24a8)
interface __BaseEnv_CloudflareEnv {
	OAUTH_KV: KVNamespace;
	ARTIFACTS: R2Bucket;
	CREATIVES: R2Bucket;
	PAYLOAD_MEDIA: R2Bucket;
	DB: D1Database;
	SYNC_TRACKED_IOS: Queue;
	SYNC_TRACKED_ANDROID: Queue;
	SYNC_ON_DEMAND_IOS: Queue;
	SYNC_ON_DEMAND_ANDROID: Queue;
	CHARTS_IOS: Queue;
	CHARTS_ANDROID: Queue;
	RECONCILE: Queue;
	CREATIVE_DISCOVERY: Queue;
	CREATIVE_MEDIA: Queue;
	AUTH_RATE_LIMITER: RateLimit;
	API_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	APP_NAME: "OpenApps";
	APP_URL: "https://apps.mbza.dev";
	ENVIRONMENT: "production";
	TRACKED_APP_REFRESH_HOURS: "24";
	CREATIVES_ENABLED: "true";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_NAME" | "APP_URL" | "ENVIRONMENT" | "TRACKED_APP_REFRESH_HOURS" | "CREATIVES_ENABLED">> {}
}
