/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AppDetailResource,
  AppKeywords200,
  AppKeywordsParams,
  AppListingParams,
  AppRankingResource,
  AppResource,
  AppSearchResultResource,
  CompareKeywordsParams,
  CompetitorGroupResource,
  CompetitorResource,
  GetRatingHistoryParams,
  KeywordCompareResource,
  ListAllCompetitorsParams,
  ListAppRankingsParams,
  ListAppsParams,
  ListingResource,
  MoveToFolderRequest,
  RatingByCountryResource,
  RatingHistoryPointResource,
  RatingSummaryResource,
  SearchAppsParams,
  StoreAppRequest,
  StoreCompetitorRequest,
  SyncStatusResource
} from '../../models';

import { orvalMutator } from '../../../lib/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List tracked apps
 */
export const listApps = (
    params?: ListAppsParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<AppResource[]>(
      {url: `/apps`, method: 'GET',
        params, signal
    },
      options);
    }




export const getListAppsQueryKey = (params?: ListAppsParams,) => {
    return [
    `/apps`, ...(params ? [params] : [])
    ] as const;
    }


export const getListAppsQueryOptions = <TData = Awaited<ReturnType<typeof listApps>>, TError = unknown>(params?: ListAppsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listApps>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAppsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listApps>>> = ({ signal }) => listApps(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listApps>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAppsQueryResult = NonNullable<Awaited<ReturnType<typeof listApps>>>
export type ListAppsQueryError = unknown


export function useListApps<TData = Awaited<ReturnType<typeof listApps>>, TError = unknown>(
 params: undefined |  ListAppsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listApps>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listApps>>,
          TError,
          Awaited<ReturnType<typeof listApps>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListApps<TData = Awaited<ReturnType<typeof listApps>>, TError = unknown>(
 params?: ListAppsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listApps>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listApps>>,
          TError,
          Awaited<ReturnType<typeof listApps>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListApps<TData = Awaited<ReturnType<typeof listApps>>, TError = unknown>(
 params?: ListAppsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listApps>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List tracked apps
 */

export function useListApps<TData = Awaited<ReturnType<typeof listApps>>, TError = unknown>(
 params?: ListAppsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listApps>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAppsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Register and track an app
 */
export const storeApp = (
    storeAppRequest: StoreAppRequest,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<AppDetailResource>(
      {url: `/apps`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: storeAppRequest, signal
    },
      options);
    }



export const getStoreAppMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof storeApp>>, TError,{data: StoreAppRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof storeApp>>, TError,{data: StoreAppRequest}, TContext> => {

const mutationKey = ['storeApp'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof storeApp>>, {data: StoreAppRequest}> = (props) => {
          const {data} = props ?? {};

          return  storeApp(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type StoreAppMutationResult = NonNullable<Awaited<ReturnType<typeof storeApp>>>
    export type StoreAppMutationBody = StoreAppRequest
    export type StoreAppMutationError = void

    /**
 * @summary Register and track an app
 */
export const useStoreApp = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof storeApp>>, TError,{data: StoreAppRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof storeApp>>,
        TError,
        {data: StoreAppRequest},
        TContext
      > => {
      return useMutation(getStoreAppMutationOptions(options), queryClient);
    }
    /**
 * @summary Get app details
 */
export const showApp = (
    platform: 'ios' | 'android',
    externalId: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<AppDetailResource>(
      {url: `/apps/${platform}/${externalId}`, method: 'GET', signal
    },
      options);
    }




export const getShowAppQueryKey = (platform: 'ios' | 'android',
    externalId: string,) => {
    return [
    `/apps/${platform}/${externalId}`
    ] as const;
    }


export const getShowAppQueryOptions = <TData = Awaited<ReturnType<typeof showApp>>, TError = unknown>(platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showApp>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getShowAppQueryKey(platform,externalId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof showApp>>> = ({ signal }) => showApp(platform,externalId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(platform && externalId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof showApp>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ShowAppQueryResult = NonNullable<Awaited<ReturnType<typeof showApp>>>
export type ShowAppQueryError = unknown


export function useShowApp<TData = Awaited<ReturnType<typeof showApp>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof showApp>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof showApp>>,
          TError,
          Awaited<ReturnType<typeof showApp>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useShowApp<TData = Awaited<ReturnType<typeof showApp>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showApp>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof showApp>>,
          TError,
          Awaited<ReturnType<typeof showApp>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useShowApp<TData = Awaited<ReturnType<typeof showApp>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showApp>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get app details
 */

export function useShowApp<TData = Awaited<ReturnType<typeof showApp>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showApp>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getShowAppQueryOptions(platform,externalId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get store listing for a specific country
 */
export const appListing = (
    platform: 'ios' | 'android',
    externalId: string,
    params: AppListingParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<ListingResource>(
      {url: `/apps/${platform}/${externalId}/listing`, method: 'GET',
        params, signal
    },
      options);
    }




export const getAppListingQueryKey = (platform: 'ios' | 'android',
    externalId: string,
    params?: AppListingParams,) => {
    return [
    `/apps/${platform}/${externalId}/listing`, ...(params ? [params] : [])
    ] as const;
    }


export const getAppListingQueryOptions = <TData = Awaited<ReturnType<typeof appListing>>, TError = unknown>(platform: 'ios' | 'android',
    externalId: string,
    params: AppListingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appListing>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAppListingQueryKey(platform,externalId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof appListing>>> = ({ signal }) => appListing(platform,externalId,params, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(platform && externalId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appListing>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AppListingQueryResult = NonNullable<Awaited<ReturnType<typeof appListing>>>
export type AppListingQueryError = unknown


export function useAppListing<TData = Awaited<ReturnType<typeof appListing>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string,
    params: AppListingParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof appListing>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof appListing>>,
          TError,
          Awaited<ReturnType<typeof appListing>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppListing<TData = Awaited<ReturnType<typeof appListing>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string,
    params: AppListingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appListing>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof appListing>>,
          TError,
          Awaited<ReturnType<typeof appListing>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppListing<TData = Awaited<ReturnType<typeof appListing>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string,
    params: AppListingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appListing>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get store listing for a specific country
 */

export function useAppListing<TData = Awaited<ReturnType<typeof appListing>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string,
    params: AppListingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appListing>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppListingQueryOptions(platform,externalId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Trigger a sync job for this app
 */
export const syncApp = (
    platform: 'ios' | 'android',
    externalId: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<SyncStatusResource>(
      {url: `/apps/${platform}/${externalId}/sync`, method: 'POST', signal
    },
      options);
    }



export const getSyncAppMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncApp>>, TError,{platform: 'ios' | 'android';externalId: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof syncApp>>, TError,{platform: 'ios' | 'android';externalId: string}, TContext> => {

const mutationKey = ['syncApp'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof syncApp>>, {platform: 'ios' | 'android';externalId: string}> = (props) => {
          const {platform,externalId} = props ?? {};

          return  syncApp(platform,externalId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SyncAppMutationResult = NonNullable<Awaited<ReturnType<typeof syncApp>>>

    export type SyncAppMutationError = unknown

    /**
 * @summary Trigger a sync job for this app
 */
export const useSyncApp = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncApp>>, TError,{platform: 'ios' | 'android';externalId: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof syncApp>>,
        TError,
        {platform: 'ios' | 'android';externalId: string},
        TContext
      > => {
      return useMutation(getSyncAppMutationOptions(options), queryClient);
    }
    /**
 * @summary Get current sync status for this app
 */
export const appSyncStatus = (
    platform: 'ios' | 'android',
    externalId: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<SyncStatusResource>(
      {url: `/apps/${platform}/${externalId}/sync-status`, method: 'GET', signal
    },
      options);
    }




export const getAppSyncStatusQueryKey = (platform: 'ios' | 'android',
    externalId: string,) => {
    return [
    `/apps/${platform}/${externalId}/sync-status`
    ] as const;
    }


export const getAppSyncStatusQueryOptions = <TData = Awaited<ReturnType<typeof appSyncStatus>>, TError = unknown>(platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appSyncStatus>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAppSyncStatusQueryKey(platform,externalId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof appSyncStatus>>> = ({ signal }) => appSyncStatus(platform,externalId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(platform && externalId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appSyncStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AppSyncStatusQueryResult = NonNullable<Awaited<ReturnType<typeof appSyncStatus>>>
export type AppSyncStatusQueryError = unknown


export function useAppSyncStatus<TData = Awaited<ReturnType<typeof appSyncStatus>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof appSyncStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof appSyncStatus>>,
          TError,
          Awaited<ReturnType<typeof appSyncStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppSyncStatus<TData = Awaited<ReturnType<typeof appSyncStatus>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appSyncStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof appSyncStatus>>,
          TError,
          Awaited<ReturnType<typeof appSyncStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppSyncStatus<TData = Awaited<ReturnType<typeof appSyncStatus>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appSyncStatus>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get current sync status for this app
 */

export function useAppSyncStatus<TData = Awaited<ReturnType<typeof appSyncStatus>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appSyncStatus>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppSyncStatusQueryOptions(platform,externalId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Track an app
 */
export const trackApp = (
    platform: 'ios' | 'android',
    externalId: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<void>(
      {url: `/apps/${platform}/${externalId}/track`, method: 'POST', signal
    },
      options);
    }



export const getTrackAppMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof trackApp>>, TError,{platform: 'ios' | 'android';externalId: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof trackApp>>, TError,{platform: 'ios' | 'android';externalId: string}, TContext> => {

const mutationKey = ['trackApp'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof trackApp>>, {platform: 'ios' | 'android';externalId: string}> = (props) => {
          const {platform,externalId} = props ?? {};

          return  trackApp(platform,externalId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TrackAppMutationResult = NonNullable<Awaited<ReturnType<typeof trackApp>>>

    export type TrackAppMutationError = unknown

    /**
 * @summary Track an app
 */
export const useTrackApp = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof trackApp>>, TError,{platform: 'ios' | 'android';externalId: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof trackApp>>,
        TError,
        {platform: 'ios' | 'android';externalId: string},
        TContext
      > => {
      return useMutation(getTrackAppMutationOptions(options), queryClient);
    }
    /**
 * @summary Untrack an app
 */
export const untrackApp = (
    platform: 'ios' | 'android',
    externalId: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<void>(
      {url: `/apps/${platform}/${externalId}/track`, method: 'DELETE', signal
    },
      options);
    }



export const getUntrackAppMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof untrackApp>>, TError,{platform: 'ios' | 'android';externalId: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof untrackApp>>, TError,{platform: 'ios' | 'android';externalId: string}, TContext> => {

const mutationKey = ['untrackApp'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof untrackApp>>, {platform: 'ios' | 'android';externalId: string}> = (props) => {
          const {platform,externalId} = props ?? {};

          return  untrackApp(platform,externalId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UntrackAppMutationResult = NonNullable<Awaited<ReturnType<typeof untrackApp>>>

    export type UntrackAppMutationError = unknown

    /**
 * @summary Untrack an app
 */
export const useUntrackApp = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof untrackApp>>, TError,{platform: 'ios' | 'android';externalId: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof untrackApp>>,
        TError,
        {platform: 'ios' | 'android';externalId: string},
        TContext
      > => {
      return useMutation(getUntrackAppMutationOptions(options), queryClient);
    }
    /**
 * @summary Move a tracked app into a folder (or remove it from its folder)
 */
export const moveAppToFolder = (
    platform: 'ios' | 'android',
    externalId: string,
    moveToFolderRequest: MoveToFolderRequest,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<void>(
      {url: `/apps/${platform}/${externalId}/folder`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: moveToFolderRequest, signal
    },
      options);
    }



export const getMoveAppToFolderMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof moveAppToFolder>>, TError,{platform: 'ios' | 'android';externalId: string;data: MoveToFolderRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof moveAppToFolder>>, TError,{platform: 'ios' | 'android';externalId: string;data: MoveToFolderRequest}, TContext> => {

const mutationKey = ['moveAppToFolder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof moveAppToFolder>>, {platform: 'ios' | 'android';externalId: string;data: MoveToFolderRequest}> = (props) => {
          const {platform,externalId,data} = props ?? {};

          return  moveAppToFolder(platform,externalId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MoveAppToFolderMutationResult = NonNullable<Awaited<ReturnType<typeof moveAppToFolder>>>
    export type MoveAppToFolderMutationBody = MoveToFolderRequest
    export type MoveAppToFolderMutationError = void

    /**
 * @summary Move a tracked app into a folder (or remove it from its folder)
 */
export const useMoveAppToFolder = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof moveAppToFolder>>, TError,{platform: 'ios' | 'android';externalId: string;data: MoveToFolderRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof moveAppToFolder>>,
        TError,
        {platform: 'ios' | 'android';externalId: string;data: MoveToFolderRequest},
        TContext
      > => {
      return useMutation(getMoveAppToFolderMutationOptions(options), queryClient);
    }
    /**
 * @summary List chart rankings for an app on a given date
 */
export const listAppRankings = (
    platform: 'ios' | 'android',
    externalId: string,
    params?: ListAppRankingsParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<AppRankingResource[]>(
      {url: `/apps/${platform}/${externalId}/rankings`, method: 'GET',
        params, signal
    },
      options);
    }




export const getListAppRankingsQueryKey = (platform: 'ios' | 'android',
    externalId: string,
    params?: ListAppRankingsParams,) => {
    return [
    `/apps/${platform}/${externalId}/rankings`, ...(params ? [params] : [])
    ] as const;
    }


export const getListAppRankingsQueryOptions = <TData = Awaited<ReturnType<typeof listAppRankings>>, TError = void>(platform: 'ios' | 'android',
    externalId: string,
    params?: ListAppRankingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAppRankings>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAppRankingsQueryKey(platform,externalId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAppRankings>>> = ({ signal }) => listAppRankings(platform,externalId,params, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(platform && externalId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAppRankings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAppRankingsQueryResult = NonNullable<Awaited<ReturnType<typeof listAppRankings>>>
export type ListAppRankingsQueryError = void


export function useListAppRankings<TData = Awaited<ReturnType<typeof listAppRankings>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params: undefined |  ListAppRankingsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAppRankings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAppRankings>>,
          TError,
          Awaited<ReturnType<typeof listAppRankings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAppRankings<TData = Awaited<ReturnType<typeof listAppRankings>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params?: ListAppRankingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAppRankings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAppRankings>>,
          TError,
          Awaited<ReturnType<typeof listAppRankings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAppRankings<TData = Awaited<ReturnType<typeof listAppRankings>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params?: ListAppRankingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAppRankings>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List chart rankings for an app on a given date
 */

export function useListAppRankings<TData = Awaited<ReturnType<typeof listAppRankings>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params?: ListAppRankingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAppRankings>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAppRankingsQueryOptions(platform,externalId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Search apps in stores
 */
export const searchApps = (
    params: SearchAppsParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<AppSearchResultResource[]>(
      {url: `/apps/search`, method: 'GET',
        params, signal
    },
      options);
    }




export const getSearchAppsQueryKey = (params?: SearchAppsParams,) => {
    return [
    `/apps/search`, ...(params ? [params] : [])
    ] as const;
    }


export const getSearchAppsQueryOptions = <TData = Awaited<ReturnType<typeof searchApps>>, TError = unknown>(params: SearchAppsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchApps>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchAppsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchApps>>> = ({ signal }) => searchApps(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchApps>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchAppsQueryResult = NonNullable<Awaited<ReturnType<typeof searchApps>>>
export type SearchAppsQueryError = unknown


export function useSearchApps<TData = Awaited<ReturnType<typeof searchApps>>, TError = unknown>(
 params: SearchAppsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchApps>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchApps>>,
          TError,
          Awaited<ReturnType<typeof searchApps>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchApps<TData = Awaited<ReturnType<typeof searchApps>>, TError = unknown>(
 params: SearchAppsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchApps>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchApps>>,
          TError,
          Awaited<ReturnType<typeof searchApps>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchApps<TData = Awaited<ReturnType<typeof searchApps>>, TError = unknown>(
 params: SearchAppsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchApps>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search apps in stores
 */

export function useSearchApps<TData = Awaited<ReturnType<typeof searchApps>>, TError = unknown>(
 params: SearchAppsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchApps>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchAppsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary List competitors for an app
 */
export const listCompetitors = (
    platform: 'ios' | 'android',
    externalId: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<CompetitorResource[]>(
      {url: `/apps/${platform}/${externalId}/competitors`, method: 'GET', signal
    },
      options);
    }




export const getListCompetitorsQueryKey = (platform: 'ios' | 'android',
    externalId: string,) => {
    return [
    `/apps/${platform}/${externalId}/competitors`
    ] as const;
    }


export const getListCompetitorsQueryOptions = <TData = Awaited<ReturnType<typeof listCompetitors>>, TError = void>(platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompetitors>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCompetitorsQueryKey(platform,externalId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCompetitors>>> = ({ signal }) => listCompetitors(platform,externalId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(platform && externalId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listCompetitors>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListCompetitorsQueryResult = NonNullable<Awaited<ReturnType<typeof listCompetitors>>>
export type ListCompetitorsQueryError = void


export function useListCompetitors<TData = Awaited<ReturnType<typeof listCompetitors>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompetitors>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCompetitors>>,
          TError,
          Awaited<ReturnType<typeof listCompetitors>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCompetitors<TData = Awaited<ReturnType<typeof listCompetitors>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompetitors>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCompetitors>>,
          TError,
          Awaited<ReturnType<typeof listCompetitors>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCompetitors<TData = Awaited<ReturnType<typeof listCompetitors>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompetitors>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List competitors for an app
 */

export function useListCompetitors<TData = Awaited<ReturnType<typeof listCompetitors>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompetitors>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListCompetitorsQueryOptions(platform,externalId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Add a competitor to an app
 */
export const storeCompetitor = (
    platform: 'ios' | 'android',
    externalId: string,
    storeCompetitorRequest: StoreCompetitorRequest,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<CompetitorResource>(
      {url: `/apps/${platform}/${externalId}/competitors`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: storeCompetitorRequest, signal
    },
      options);
    }



export const getStoreCompetitorMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof storeCompetitor>>, TError,{platform: 'ios' | 'android';externalId: string;data: StoreCompetitorRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof storeCompetitor>>, TError,{platform: 'ios' | 'android';externalId: string;data: StoreCompetitorRequest}, TContext> => {

const mutationKey = ['storeCompetitor'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof storeCompetitor>>, {platform: 'ios' | 'android';externalId: string;data: StoreCompetitorRequest}> = (props) => {
          const {platform,externalId,data} = props ?? {};

          return  storeCompetitor(platform,externalId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type StoreCompetitorMutationResult = NonNullable<Awaited<ReturnType<typeof storeCompetitor>>>
    export type StoreCompetitorMutationBody = StoreCompetitorRequest
    export type StoreCompetitorMutationError = void

    /**
 * @summary Add a competitor to an app
 */
export const useStoreCompetitor = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof storeCompetitor>>, TError,{platform: 'ios' | 'android';externalId: string;data: StoreCompetitorRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof storeCompetitor>>,
        TError,
        {platform: 'ios' | 'android';externalId: string;data: StoreCompetitorRequest},
        TContext
      > => {
      return useMutation(getStoreCompetitorMutationOptions(options), queryClient);
    }
    /**
 * @summary List competitors grouped by parent app across all user apps
 */
export const listAllCompetitors = (
    params?: ListAllCompetitorsParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<CompetitorGroupResource[]>(
      {url: `/competitors`, method: 'GET',
        params, signal
    },
      options);
    }




export const getListAllCompetitorsQueryKey = (params?: ListAllCompetitorsParams,) => {
    return [
    `/competitors`, ...(params ? [params] : [])
    ] as const;
    }


export const getListAllCompetitorsQueryOptions = <TData = Awaited<ReturnType<typeof listAllCompetitors>>, TError = unknown>(params?: ListAllCompetitorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllCompetitors>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAllCompetitorsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAllCompetitors>>> = ({ signal }) => listAllCompetitors(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAllCompetitors>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAllCompetitorsQueryResult = NonNullable<Awaited<ReturnType<typeof listAllCompetitors>>>
export type ListAllCompetitorsQueryError = unknown


export function useListAllCompetitors<TData = Awaited<ReturnType<typeof listAllCompetitors>>, TError = unknown>(
 params: undefined |  ListAllCompetitorsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllCompetitors>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAllCompetitors>>,
          TError,
          Awaited<ReturnType<typeof listAllCompetitors>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAllCompetitors<TData = Awaited<ReturnType<typeof listAllCompetitors>>, TError = unknown>(
 params?: ListAllCompetitorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllCompetitors>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAllCompetitors>>,
          TError,
          Awaited<ReturnType<typeof listAllCompetitors>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAllCompetitors<TData = Awaited<ReturnType<typeof listAllCompetitors>>, TError = unknown>(
 params?: ListAllCompetitorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllCompetitors>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List competitors grouped by parent app across all user apps
 */

export function useListAllCompetitors<TData = Awaited<ReturnType<typeof listAllCompetitors>>, TError = unknown>(
 params?: ListAllCompetitorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllCompetitors>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAllCompetitorsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Remove a competitor from an app
 */
export const deleteCompetitor = (
    platform: 'ios' | 'android',
    externalId: string,
    competitor: number,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<void>(
      {url: `/apps/${platform}/${externalId}/competitors/${competitor}`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteCompetitorMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCompetitor>>, TError,{platform: 'ios' | 'android';externalId: string;competitor: number}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCompetitor>>, TError,{platform: 'ios' | 'android';externalId: string;competitor: number}, TContext> => {

const mutationKey = ['deleteCompetitor'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCompetitor>>, {platform: 'ios' | 'android';externalId: string;competitor: number}> = (props) => {
          const {platform,externalId,competitor} = props ?? {};

          return  deleteCompetitor(platform,externalId,competitor,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteCompetitorMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCompetitor>>>

    export type DeleteCompetitorMutationError = void

    /**
 * @summary Remove a competitor from an app
 */
export const useDeleteCompetitor = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCompetitor>>, TError,{platform: 'ios' | 'android';externalId: string;competitor: number}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCompetitor>>,
        TError,
        {platform: 'ios' | 'android';externalId: string;competitor: number},
        TContext
      > => {
      return useMutation(getDeleteCompetitorMutationOptions(options), queryClient);
    }
    /**
 * @summary Get keyword density for an app
 */
export const appKeywords = (
    platform: 'ios' | 'android',
    externalId: string,
    params?: AppKeywordsParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<AppKeywords200>(
      {url: `/apps/${platform}/${externalId}/keywords`, method: 'GET',
        params, signal
    },
      options);
    }




export const getAppKeywordsQueryKey = (platform: 'ios' | 'android',
    externalId: string,
    params?: AppKeywordsParams,) => {
    return [
    `/apps/${platform}/${externalId}/keywords`, ...(params ? [params] : [])
    ] as const;
    }


export const getAppKeywordsQueryOptions = <TData = Awaited<ReturnType<typeof appKeywords>>, TError = void>(platform: 'ios' | 'android',
    externalId: string,
    params?: AppKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appKeywords>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAppKeywordsQueryKey(platform,externalId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof appKeywords>>> = ({ signal }) => appKeywords(platform,externalId,params, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(platform && externalId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appKeywords>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AppKeywordsQueryResult = NonNullable<Awaited<ReturnType<typeof appKeywords>>>
export type AppKeywordsQueryError = void


export function useAppKeywords<TData = Awaited<ReturnType<typeof appKeywords>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params: undefined |  AppKeywordsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof appKeywords>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof appKeywords>>,
          TError,
          Awaited<ReturnType<typeof appKeywords>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppKeywords<TData = Awaited<ReturnType<typeof appKeywords>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params?: AppKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appKeywords>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof appKeywords>>,
          TError,
          Awaited<ReturnType<typeof appKeywords>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppKeywords<TData = Awaited<ReturnType<typeof appKeywords>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params?: AppKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appKeywords>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get keyword density for an app
 */

export function useAppKeywords<TData = Awaited<ReturnType<typeof appKeywords>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params?: AppKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appKeywords>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppKeywordsQueryOptions(platform,externalId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Compare keyword density with other apps
 */
export const compareKeywords = (
    platform: 'ios' | 'android',
    externalId: string,
    params: CompareKeywordsParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<KeywordCompareResource>(
      {url: `/apps/${platform}/${externalId}/keywords/compare`, method: 'GET',
        params, signal
    },
      options);
    }




export const getCompareKeywordsQueryKey = (platform: 'ios' | 'android',
    externalId: string,
    params?: CompareKeywordsParams,) => {
    return [
    `/apps/${platform}/${externalId}/keywords/compare`, ...(params ? [params] : [])
    ] as const;
    }


export const getCompareKeywordsQueryOptions = <TData = Awaited<ReturnType<typeof compareKeywords>>, TError = void>(platform: 'ios' | 'android',
    externalId: string,
    params: CompareKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof compareKeywords>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCompareKeywordsQueryKey(platform,externalId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof compareKeywords>>> = ({ signal }) => compareKeywords(platform,externalId,params, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(platform && externalId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof compareKeywords>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CompareKeywordsQueryResult = NonNullable<Awaited<ReturnType<typeof compareKeywords>>>
export type CompareKeywordsQueryError = void


export function useCompareKeywords<TData = Awaited<ReturnType<typeof compareKeywords>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params: CompareKeywordsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof compareKeywords>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof compareKeywords>>,
          TError,
          Awaited<ReturnType<typeof compareKeywords>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCompareKeywords<TData = Awaited<ReturnType<typeof compareKeywords>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params: CompareKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof compareKeywords>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof compareKeywords>>,
          TError,
          Awaited<ReturnType<typeof compareKeywords>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCompareKeywords<TData = Awaited<ReturnType<typeof compareKeywords>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params: CompareKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof compareKeywords>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Compare keyword density with other apps
 */

export function useCompareKeywords<TData = Awaited<ReturnType<typeof compareKeywords>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params: CompareKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof compareKeywords>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCompareKeywordsQueryOptions(platform,externalId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get the rating summary (current rating + 30-day trend)
 */
export const getRatingSummary = (
    platform: 'ios' | 'android',
    externalId: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<RatingSummaryResource>(
      {url: `/apps/${platform}/${externalId}/ratings/summary`, method: 'GET', signal
    },
      options);
    }




export const getGetRatingSummaryQueryKey = (platform: 'ios' | 'android',
    externalId: string,) => {
    return [
    `/apps/${platform}/${externalId}/ratings/summary`
    ] as const;
    }


export const getGetRatingSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getRatingSummary>>, TError = void>(platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRatingSummary>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRatingSummaryQueryKey(platform,externalId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRatingSummary>>> = ({ signal }) => getRatingSummary(platform,externalId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(platform && externalId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRatingSummary>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRatingSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getRatingSummary>>>
export type GetRatingSummaryQueryError = void


export function useGetRatingSummary<TData = Awaited<ReturnType<typeof getRatingSummary>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRatingSummary>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRatingSummary>>,
          TError,
          Awaited<ReturnType<typeof getRatingSummary>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRatingSummary<TData = Awaited<ReturnType<typeof getRatingSummary>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRatingSummary>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRatingSummary>>,
          TError,
          Awaited<ReturnType<typeof getRatingSummary>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRatingSummary<TData = Awaited<ReturnType<typeof getRatingSummary>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRatingSummary>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get the rating summary (current rating + 30-day trend)
 */

export function useGetRatingSummary<TData = Awaited<ReturnType<typeof getRatingSummary>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRatingSummary>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRatingSummaryQueryOptions(platform,externalId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get daily rating history (last N days)
 */
export const getRatingHistory = (
    platform: 'ios' | 'android',
    externalId: string,
    params?: GetRatingHistoryParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<RatingHistoryPointResource[]>(
      {url: `/apps/${platform}/${externalId}/ratings/history`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetRatingHistoryQueryKey = (platform: 'ios' | 'android',
    externalId: string,
    params?: GetRatingHistoryParams,) => {
    return [
    `/apps/${platform}/${externalId}/ratings/history`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetRatingHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getRatingHistory>>, TError = void>(platform: 'ios' | 'android',
    externalId: string,
    params?: GetRatingHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRatingHistory>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRatingHistoryQueryKey(platform,externalId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRatingHistory>>> = ({ signal }) => getRatingHistory(platform,externalId,params, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(platform && externalId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRatingHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRatingHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getRatingHistory>>>
export type GetRatingHistoryQueryError = void


export function useGetRatingHistory<TData = Awaited<ReturnType<typeof getRatingHistory>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params: undefined |  GetRatingHistoryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRatingHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRatingHistory>>,
          TError,
          Awaited<ReturnType<typeof getRatingHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRatingHistory<TData = Awaited<ReturnType<typeof getRatingHistory>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params?: GetRatingHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRatingHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRatingHistory>>,
          TError,
          Awaited<ReturnType<typeof getRatingHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRatingHistory<TData = Awaited<ReturnType<typeof getRatingHistory>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params?: GetRatingHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRatingHistory>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get daily rating history (last N days)
 */

export function useGetRatingHistory<TData = Awaited<ReturnType<typeof getRatingHistory>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params?: GetRatingHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRatingHistory>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRatingHistoryQueryOptions(platform,externalId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get the latest rating snapshot per country (iOS only)
 */
export const getRatingCountryBreakdown = (
    platform: 'ios' | 'android',
    externalId: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<RatingByCountryResource[]>(
      {url: `/apps/${platform}/${externalId}/ratings/country-breakdown`, method: 'GET', signal
    },
      options);
    }




export const getGetRatingCountryBreakdownQueryKey = (platform: 'ios' | 'android',
    externalId: string,) => {
    return [
    `/apps/${platform}/${externalId}/ratings/country-breakdown`
    ] as const;
    }


export const getGetRatingCountryBreakdownQueryOptions = <TData = Awaited<ReturnType<typeof getRatingCountryBreakdown>>, TError = void>(platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRatingCountryBreakdown>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRatingCountryBreakdownQueryKey(platform,externalId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRatingCountryBreakdown>>> = ({ signal }) => getRatingCountryBreakdown(platform,externalId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(platform && externalId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRatingCountryBreakdown>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRatingCountryBreakdownQueryResult = NonNullable<Awaited<ReturnType<typeof getRatingCountryBreakdown>>>
export type GetRatingCountryBreakdownQueryError = void


export function useGetRatingCountryBreakdown<TData = Awaited<ReturnType<typeof getRatingCountryBreakdown>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRatingCountryBreakdown>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRatingCountryBreakdown>>,
          TError,
          Awaited<ReturnType<typeof getRatingCountryBreakdown>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRatingCountryBreakdown<TData = Awaited<ReturnType<typeof getRatingCountryBreakdown>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRatingCountryBreakdown>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRatingCountryBreakdown>>,
          TError,
          Awaited<ReturnType<typeof getRatingCountryBreakdown>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRatingCountryBreakdown<TData = Awaited<ReturnType<typeof getRatingCountryBreakdown>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRatingCountryBreakdown>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get the latest rating snapshot per country (iOS only)
 */

export function useGetRatingCountryBreakdown<TData = Awaited<ReturnType<typeof getRatingCountryBreakdown>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRatingCountryBreakdown>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRatingCountryBreakdownQueryOptions(platform,externalId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




