/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ImportPublisherAppsBody,
  PublisherDetailResource,
  PublisherResource,
  PublisherSearchResultResource,
  PublisherStoreApps200,
  SearchPublishersParams,
  ShowPublisherParams
} from '../../models';

import { orvalMutator } from '../../../lib/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Search publishers across stores
 */
export const searchPublishers = (
    params: SearchPublishersParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<PublisherSearchResultResource[]>(
      {url: `/publishers/search`, method: 'GET',
        params, signal
    },
      options);
    }




export const getSearchPublishersQueryKey = (params?: SearchPublishersParams,) => {
    return [
    `/publishers/search`, ...(params ? [params] : [])
    ] as const;
    }


export const getSearchPublishersQueryOptions = <TData = Awaited<ReturnType<typeof searchPublishers>>, TError = unknown>(params: SearchPublishersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPublishers>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchPublishersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchPublishers>>> = ({ signal }) => searchPublishers(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchPublishers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchPublishersQueryResult = NonNullable<Awaited<ReturnType<typeof searchPublishers>>>
export type SearchPublishersQueryError = unknown


export function useSearchPublishers<TData = Awaited<ReturnType<typeof searchPublishers>>, TError = unknown>(
 params: SearchPublishersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPublishers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchPublishers>>,
          TError,
          Awaited<ReturnType<typeof searchPublishers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchPublishers<TData = Awaited<ReturnType<typeof searchPublishers>>, TError = unknown>(
 params: SearchPublishersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPublishers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchPublishers>>,
          TError,
          Awaited<ReturnType<typeof searchPublishers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchPublishers<TData = Awaited<ReturnType<typeof searchPublishers>>, TError = unknown>(
 params: SearchPublishersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPublishers>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search publishers across stores
 */

export function useSearchPublishers<TData = Awaited<ReturnType<typeof searchPublishers>>, TError = unknown>(
 params: SearchPublishersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPublishers>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchPublishersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary List publishers from user apps
 */
export const listPublishers = (

 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<PublisherResource[]>(
      {url: `/publishers`, method: 'GET', signal
    },
      options);
    }




export const getListPublishersQueryKey = () => {
    return [
    `/publishers`
    ] as const;
    }


export const getListPublishersQueryOptions = <TData = Awaited<ReturnType<typeof listPublishers>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPublishers>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPublishersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPublishers>>> = ({ signal }) => listPublishers(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPublishers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPublishersQueryResult = NonNullable<Awaited<ReturnType<typeof listPublishers>>>
export type ListPublishersQueryError = unknown


export function useListPublishers<TData = Awaited<ReturnType<typeof listPublishers>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPublishers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPublishers>>,
          TError,
          Awaited<ReturnType<typeof listPublishers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPublishers<TData = Awaited<ReturnType<typeof listPublishers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPublishers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPublishers>>,
          TError,
          Awaited<ReturnType<typeof listPublishers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPublishers<TData = Awaited<ReturnType<typeof listPublishers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPublishers>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List publishers from user apps
 */

export function useListPublishers<TData = Awaited<ReturnType<typeof listPublishers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPublishers>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPublishersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get publisher details with tracked apps
 */
export const showPublisher = (
    platform: 'ios' | 'android',
    externalId: string,
    params?: ShowPublisherParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<PublisherDetailResource>(
      {url: `/publishers/${platform}/${externalId}`, method: 'GET',
        params, signal
    },
      options);
    }




export const getShowPublisherQueryKey = (platform: 'ios' | 'android',
    externalId: string,
    params?: ShowPublisherParams,) => {
    return [
    `/publishers/${platform}/${externalId}`, ...(params ? [params] : [])
    ] as const;
    }


export const getShowPublisherQueryOptions = <TData = Awaited<ReturnType<typeof showPublisher>>, TError = unknown>(platform: 'ios' | 'android',
    externalId: string,
    params?: ShowPublisherParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showPublisher>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getShowPublisherQueryKey(platform,externalId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof showPublisher>>> = ({ signal }) => showPublisher(platform,externalId,params, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(platform && externalId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof showPublisher>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ShowPublisherQueryResult = NonNullable<Awaited<ReturnType<typeof showPublisher>>>
export type ShowPublisherQueryError = unknown


export function useShowPublisher<TData = Awaited<ReturnType<typeof showPublisher>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string,
    params: undefined |  ShowPublisherParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof showPublisher>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof showPublisher>>,
          TError,
          Awaited<ReturnType<typeof showPublisher>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useShowPublisher<TData = Awaited<ReturnType<typeof showPublisher>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string,
    params?: ShowPublisherParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showPublisher>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof showPublisher>>,
          TError,
          Awaited<ReturnType<typeof showPublisher>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useShowPublisher<TData = Awaited<ReturnType<typeof showPublisher>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string,
    params?: ShowPublisherParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showPublisher>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get publisher details with tracked apps
 */

export function useShowPublisher<TData = Awaited<ReturnType<typeof showPublisher>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string,
    params?: ShowPublisherParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showPublisher>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getShowPublisherQueryOptions(platform,externalId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Fetch all apps by publisher from store
 */
export const publisherStoreApps = (
    platform: 'ios' | 'android',
    externalId: string,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<PublisherStoreApps200>(
      {url: `/publishers/${platform}/${externalId}/store-apps`, method: 'GET', signal
    },
      options);
    }




export const getPublisherStoreAppsQueryKey = (platform: 'ios' | 'android',
    externalId: string,) => {
    return [
    `/publishers/${platform}/${externalId}/store-apps`
    ] as const;
    }


export const getPublisherStoreAppsQueryOptions = <TData = Awaited<ReturnType<typeof publisherStoreApps>>, TError = unknown>(platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publisherStoreApps>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPublisherStoreAppsQueryKey(platform,externalId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof publisherStoreApps>>> = ({ signal }) => publisherStoreApps(platform,externalId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(platform && externalId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof publisherStoreApps>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PublisherStoreAppsQueryResult = NonNullable<Awaited<ReturnType<typeof publisherStoreApps>>>
export type PublisherStoreAppsQueryError = unknown


export function usePublisherStoreApps<TData = Awaited<ReturnType<typeof publisherStoreApps>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof publisherStoreApps>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publisherStoreApps>>,
          TError,
          Awaited<ReturnType<typeof publisherStoreApps>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePublisherStoreApps<TData = Awaited<ReturnType<typeof publisherStoreApps>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publisherStoreApps>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publisherStoreApps>>,
          TError,
          Awaited<ReturnType<typeof publisherStoreApps>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePublisherStoreApps<TData = Awaited<ReturnType<typeof publisherStoreApps>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publisherStoreApps>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fetch all apps by publisher from store
 */

export function usePublisherStoreApps<TData = Awaited<ReturnType<typeof publisherStoreApps>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publisherStoreApps>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPublisherStoreAppsQueryOptions(platform,externalId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Import and track apps from publisher
 */
export const importPublisherApps = (
    platform: 'ios' | 'android',
    externalId: string,
    importPublisherAppsBody: ImportPublisherAppsBody,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<void>(
      {url: `/publishers/${platform}/${externalId}/import`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: importPublisherAppsBody, signal
    },
      options);
    }



export const getImportPublisherAppsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importPublisherApps>>, TError,{platform: 'ios' | 'android';externalId: string;data: ImportPublisherAppsBody}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof importPublisherApps>>, TError,{platform: 'ios' | 'android';externalId: string;data: ImportPublisherAppsBody}, TContext> => {

const mutationKey = ['importPublisherApps'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof importPublisherApps>>, {platform: 'ios' | 'android';externalId: string;data: ImportPublisherAppsBody}> = (props) => {
          const {platform,externalId,data} = props ?? {};

          return  importPublisherApps(platform,externalId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ImportPublisherAppsMutationResult = NonNullable<Awaited<ReturnType<typeof importPublisherApps>>>
    export type ImportPublisherAppsMutationBody = ImportPublisherAppsBody
    export type ImportPublisherAppsMutationError = unknown

    /**
 * @summary Import and track apps from publisher
 */
export const useImportPublisherApps = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importPublisherApps>>, TError,{platform: 'ios' | 'android';externalId: string;data: ImportPublisherAppsBody}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof importPublisherApps>>,
        TError,
        {platform: 'ios' | 'android';externalId: string;data: ImportPublisherAppsBody},
        TContext
      > => {
      return useMutation(getImportPublisherAppsMutationOptions(options), queryClient);
    }
