/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ListStoreCategoriesParams,
  StoreCategoryResource
} from '../../models';

import { orvalMutator } from '../../../lib/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List store categories
 */
export const listStoreCategories = (
    params?: ListStoreCategoriesParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<StoreCategoryResource[]>(
      {url: `/store-categories`, method: 'GET',
        params, signal
    },
      options);
    }




export const getListStoreCategoriesQueryKey = (params?: ListStoreCategoriesParams,) => {
    return [
    `/store-categories`, ...(params ? [params] : [])
    ] as const;
    }


export const getListStoreCategoriesQueryOptions = <TData = Awaited<ReturnType<typeof listStoreCategories>>, TError = unknown>(params?: ListStoreCategoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStoreCategories>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListStoreCategoriesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listStoreCategories>>> = ({ signal }) => listStoreCategories(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listStoreCategories>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListStoreCategoriesQueryResult = NonNullable<Awaited<ReturnType<typeof listStoreCategories>>>
export type ListStoreCategoriesQueryError = unknown


export function useListStoreCategories<TData = Awaited<ReturnType<typeof listStoreCategories>>, TError = unknown>(
 params: undefined |  ListStoreCategoriesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStoreCategories>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStoreCategories>>,
          TError,
          Awaited<ReturnType<typeof listStoreCategories>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStoreCategories<TData = Awaited<ReturnType<typeof listStoreCategories>>, TError = unknown>(
 params?: ListStoreCategoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStoreCategories>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStoreCategories>>,
          TError,
          Awaited<ReturnType<typeof listStoreCategories>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStoreCategories<TData = Awaited<ReturnType<typeof listStoreCategories>>, TError = unknown>(
 params?: ListStoreCategoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStoreCategories>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List store categories
 */

export function useListStoreCategories<TData = Awaited<ReturnType<typeof listStoreCategories>>, TError = unknown>(
 params?: ListStoreCategoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStoreCategories>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListStoreCategoriesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




