/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetCharts200,
  GetChartsParams
} from '../../models';

import { orvalMutator } from '../../../lib/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get chart rankings
 */
export const getCharts = (
    params: GetChartsParams,
 options?: SecondParameter<typeof orvalMutator>,signal?: AbortSignal
) => {


      return orvalMutator<GetCharts200>(
      {url: `/charts`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetChartsQueryKey = (params?: GetChartsParams,) => {
    return [
    `/charts`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetChartsQueryOptions = <TData = Awaited<ReturnType<typeof getCharts>>, TError = unknown>(params: GetChartsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCharts>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetChartsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCharts>>> = ({ signal }) => getCharts(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCharts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetChartsQueryResult = NonNullable<Awaited<ReturnType<typeof getCharts>>>
export type GetChartsQueryError = unknown


export function useGetCharts<TData = Awaited<ReturnType<typeof getCharts>>, TError = unknown>(
 params: GetChartsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCharts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCharts>>,
          TError,
          Awaited<ReturnType<typeof getCharts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCharts<TData = Awaited<ReturnType<typeof getCharts>>, TError = unknown>(
 params: GetChartsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCharts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCharts>>,
          TError,
          Awaited<ReturnType<typeof getCharts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCharts<TData = Awaited<ReturnType<typeof getCharts>>, TError = unknown>(
 params: GetChartsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCharts>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get chart rankings
 */

export function useGetCharts<TData = Awaited<ReturnType<typeof getCharts>>, TError = unknown>(
 params: GetChartsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCharts>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetChartsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




