/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { AppPlatform } from './appPlatform';
import type { Publisher } from './publisher';
import type { StoreCategory } from './storeCategory';

export interface App {
  id: number;
  platform: AppPlatform;
  external_id: string;
  /** @nullable */
  display_name?: string | null;
  /** @nullable */
  icon_url?: string | null;
  origin_country_code?: string;
  /** @nullable */
  supported_locales?: string[] | null;
  /** @nullable */
  original_release_date?: string | null;
  is_free?: boolean;
  is_available?: boolean;
  publisher?: Publisher | null;
  category?: StoreCategory | null;
  created_at?: string;
  updated_at?: string;
}
