/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { AppChangesField } from './appChangesField';
import type { AppChangesPlatform } from './appChangesPlatform';

export type AppChangesParams = {
per_page?: number;
page?: number;
field?: AppChangesField;
platform?: AppChangesPlatform;
/**
 * @maxLength 100
 */
search?: string;
/**
 * @minimum 1
 */
app_id?: number;
/**
 * Filter by the tracked app's folder. Pass an integer for a specific folder, `null` or `unassigned` for tracked apps without a folder, or omit for all tracked apps.
 * @nullable
 */
folder_id?: string | null;
};
