/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { CompetitorRelationship } from './competitorRelationship';

export interface AppCompetitor {
  id: number;
  app_id: number;
  competitor_app_id: number;
  relationship: CompetitorRelationship;
  created_at?: string;
  updated_at?: string;
}
