/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { AppChanges200Links } from './appChanges200Links';
import type { AppChanges200Meta } from './appChanges200Meta';
import type { ChangeResource } from './changeResource';

export type AppChanges200 = {
  data?: ChangeResource[];
  links?: AppChanges200Links;
  meta?: AppChanges200Meta;
};
