/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { App } from './app';
import type { CompetitorResource } from './competitorResource';
import type { ListingResource } from './listingResource';
import type { StoreListingChange } from './storeListingChange';
import type { VersionResource } from './versionResource';

export type AppDetailResource = App & ({
  name: string;
  /** @nullable */
  rating?: number | null;
  /** @nullable */
  rating_count?: number | null;
  /** @nullable */
  version?: string | null;
  /** @nullable */
  file_size_bytes?: number | null;
  is_tracked?: boolean;
  /** Country codes where this app is not listed on the store. */
  unavailable_countries?: string[];
  listings?: ListingResource[];
  versions?: VersionResource[];
  changes?: StoreListingChange[];
  competitors?: CompetitorResource[];
});
