/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { AppKeywordsNgram } from './appKeywordsNgram';
import type { AppKeywordsOrder } from './appKeywordsOrder';
import type { AppKeywordsSort } from './appKeywordsSort';

export type AppKeywordsParams = {
locale?: string;
ngram?: AppKeywordsNgram;
version_id?: number;
/**
 * @maxLength 100
 */
search?: string;
sort?: AppKeywordsSort;
order?: AppKeywordsOrder;
/**
 * @minimum 1
 * @maximum 500
 */
per_page?: number;
/**
 * @minimum 1
 */
page?: number;
};
