/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { App } from './app';

export type AppResource = App & ({
  name: string;
  /** @nullable */
  rating?: number | null;
  /** @nullable */
  rating_count?: number | null;
  /** @nullable */
  version?: string | null;
  is_tracked?: boolean;
});
