/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type AppRankingIndexRequestCollection = typeof AppRankingIndexRequestCollection[keyof typeof AppRankingIndexRequestCollection] | null;


export const AppRankingIndexRequestCollection = {
  top_free: 'top_free',
  top_paid: 'top_paid',
  top_grossing: 'top_grossing',
  all: 'all',
} as const;
