/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { AppSearchRequestPlatform } from './appSearchRequestPlatform';

export interface AppSearchRequest {
  /**
     * @minLength 2
     * @maxLength 100
     */
  term: string;
  platform: AppSearchRequestPlatform;
  /**
     * @minLength 2
     * @maxLength 2
     */
  country_code?: string;
  /** @nullable */
  exclude_external_ids?: string[] | null;
}
