/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */

export type BuildStatus = typeof BuildStatus[keyof typeof BuildStatus];


export const BuildStatus = {
  pending: 'pending',
  fetching_identity: 'fetching_identity',
  fetching_listings: 'fetching_listings',
  fetching_metrics: 'fetching_metrics',
  fetching_reviews: 'fetching_reviews',
  analyzing_reviews: 'analyzing_reviews',
  analyzing_listings: 'analyzing_listings',
  fetching_versions: 'fetching_versions',
  completed: 'completed',
  failed: 'failed',
} as const;
