/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */

export interface BuildStatusResource {
  build_status: string;
  /** @nullable */
  build_error?: string | null;
  /** @nullable */
  last_build_at?: string | null;
}
