/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { ChangeCompetitorsRequestField } from './changeCompetitorsRequestField';
import type { ChangeCompetitorsRequestPlatform } from './changeCompetitorsRequestPlatform';

export interface ChangeCompetitorsRequest {
  /**
     * @minimum 1
     * @maximum 100
     * @nullable
     */
  per_page?: number | null;
  /** @nullable */
  field?: ChangeCompetitorsRequestField;
  /** @nullable */
  platform?: ChangeCompetitorsRequestPlatform;
  /**
     * @maxLength 100
     * @nullable
     */
  search?: string | null;
  /**
     * @minimum 1
     * @nullable
     */
  app_id?: number | null;
  /**
     * @minimum 1
     * @nullable
     */
  page?: number | null;
  /**
     * Filter by the parent (tracked) app's folder. Pass an integer for a specific folder, `null` or `unassigned` for tracked apps without a folder, or omit for all competitors.
     * @nullable
     */
  folder_id?: string | null;
}
