/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type ChangeCompetitorsRequestField = typeof ChangeCompetitorsRequestField[keyof typeof ChangeCompetitorsRequestField] | null;


export const ChangeCompetitorsRequestField = {
  title: 'title',
  subtitle: 'subtitle',
  description: 'description',
  whats_new: 'whats_new',
  screenshots: 'screenshots',
  locale_added: 'locale_added',
  locale_removed: 'locale_removed',
} as const;
