/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { ChangeResourceApp } from './changeResourceApp';
import type { StoreListingChange } from './storeListingChange';

export type ChangeResource = StoreListingChange & ({
  /** @nullable */
  app?: ChangeResourceApp;
  /** @nullable */
  version?: string | null;
  /** @nullable */
  previous_version?: string | null;
});
