/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */

export type ChartIndexRequestCollection = typeof ChartIndexRequestCollection[keyof typeof ChartIndexRequestCollection];


export const ChartIndexRequestCollection = {
  top_free: 'top_free',
  top_paid: 'top_paid',
  top_grossing: 'top_grossing',
} as const;
