/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { ChartIndexRequestCollection } from './chartIndexRequestCollection';
import type { ChartIndexRequestPlatform } from './chartIndexRequestPlatform';

export interface ChartIndexRequest {
  platform: ChartIndexRequestPlatform;
  collection: ChartIndexRequestCollection;
  /**
     * @minLength 2
     * @maxLength 2
     * @nullable
     */
  country_code?: string | null;
  /** @nullable */
  category_id?: number | null;
}
