/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { ChartEntryResourcePlatform } from './chartEntryResourcePlatform';
import type { ChartEntryResourcePublisher } from './chartEntryResourcePublisher';

export interface ChartEntryResource {
  rank?: number;
  /** @nullable */
  rank_change?: number | null;
  app_id?: number;
  app_external_id?: string;
  app_name?: string;
  /** @nullable */
  icon_url?: string | null;
  platform?: ChartEntryResourcePlatform;
  /** @nullable */
  publisher?: ChartEntryResourcePublisher;
  /** @nullable */
  category_name?: string | null;
  price?: number;
  /** @nullable */
  currency?: string | null;
  is_free?: boolean;
}
