/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { ChangeResource } from './changeResource';
import type { CompetitorChanges200Links } from './competitorChanges200Links';
import type { CompetitorChanges200Meta } from './competitorChanges200Meta';

export type CompetitorChanges200 = {
  data?: ChangeResource[];
  links?: CompetitorChanges200Links;
  meta?: CompetitorChanges200Meta;
};
