/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { CompetitorChangesField } from './competitorChangesField';
import type { CompetitorChangesPlatform } from './competitorChangesPlatform';

export type CompetitorChangesParams = {
per_page?: number;
page?: number;
field?: CompetitorChangesField;
platform?: CompetitorChangesPlatform;
/**
 * @maxLength 100
 */
search?: string;
/**
 * @minimum 1
 */
app_id?: number;
/**
 * Filter by the parent (tracked) app's folder. Pass an integer for a specific folder, `null` or `unassigned` for tracked apps without a folder, or omit for all competitors.
 * @nullable
 */
folder_id?: string | null;
};
