/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { CompareKeywordsNgram } from './compareKeywordsNgram';

export type CompareKeywordsParams = {
/**
 * App IDs to compare (max 5)
 */
app_ids: number[];
/**
 * Version ID per app (keyed by app ID)
 */
version_ids?: {[key: string]: number};
locale?: string;
ngram?: CompareKeywordsNgram;
};
