/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { Dashboard200RecentChangesItem } from './dashboard200RecentChangesItem';

export type Dashboard200 = {
  total_apps?: number;
  total_versions?: number;
  total_changes?: number;
  recent_changes?: Dashboard200RecentChangesItem[];
};
