/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { ExplorerScreenshotsRequestPlatform } from './explorerScreenshotsRequestPlatform';

export interface ExplorerScreenshotsRequest {
  /** @nullable */
  platform?: ExplorerScreenshotsRequestPlatform;
  /** @nullable */
  category_id?: number | null;
  /**
     * @maxLength 100
     * @nullable
     */
  search?: string | null;
  /**
     * @minimum 1
     * @maximum 50
     * @nullable
     */
  per_page?: number | null;
}
