/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { ExploreScreenshotsPlatform } from './exploreScreenshotsPlatform';

export type ExploreScreenshotsParams = {
platform?: ExploreScreenshotsPlatform;
category_id?: number;
search?: string;
per_page?: number;
page?: number;
};
