/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { ExplorerScreenshotResource } from './explorerScreenshotResource';
import type { ExploreScreenshots200Links } from './exploreScreenshots200Links';
import type { ExploreScreenshots200Meta } from './exploreScreenshots200Meta';

export type ExploreScreenshots200 = {
  data?: ExplorerScreenshotResource[];
  links?: ExploreScreenshots200Links;
  meta?: ExploreScreenshots200Meta;
};
