/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Folder color slug; resolved to Tailwind classes on the client.
 */
export type FolderColorEnum = typeof FolderColorEnum[keyof typeof FolderColorEnum];


export const FolderColorEnum = {
  slate: 'slate',
  red: 'red',
  orange: 'orange',
  amber: 'amber',
  yellow: 'yellow',
  green: 'green',
  teal: 'teal',
  blue: 'blue',
  purple: 'purple',
  pink: 'pink',
} as const;
