/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */

export type GetCharts200MetaPlatform = typeof GetCharts200MetaPlatform[keyof typeof GetCharts200MetaPlatform];


export const GetCharts200MetaPlatform = {
  ios: 'ios',
  android: 'android',
} as const;
