/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type KeywordIndexRequestSort = typeof KeywordIndexRequestSort[keyof typeof KeywordIndexRequestSort] | null;


export const KeywordIndexRequestSort = {
  keyword: 'keyword',
  count: 'count',
  density: 'density',
} as const;
