/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { ListAppsPlatform } from './listAppsPlatform';

export type ListAppsParams = {
platform?: ListAppsPlatform;
/**
 * @maxLength 100
 */
search?: string;
/**
 * Filter by folder. Pass an integer for a specific folder, `null` or `unassigned` for tracked apps with no folder, or omit for all tracked apps.
 * @nullable
 */
folder_id?: string | null;
};
