/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { ListAllCompetitorsPlatform } from './listAllCompetitorsPlatform';

export type ListAllCompetitorsParams = {
platform?: ListAllCompetitorsPlatform;
/**
 * @maxLength 100
 */
search?: string;
/**
 * Filter by the parent app's folder. Pass an integer for a specific folder, `null` or `unassigned` for tracked apps without a folder, or omit to include every parent.
 * @nullable
 */
folder_id?: string | null;
};
