/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */

export interface MoveToFolderRequest {
  /**
     * Target folder id, or null to remove the app from its current folder.
     * @nullable
     */
  folder_id: number | null;
}
