/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { ChangeResource } from './changeResource';
import type { PaginatedChangeResponseLinks } from './paginatedChangeResponseLinks';
import type { PaginatedChangeResponseMeta } from './paginatedChangeResponseMeta';
import type { PaginatedChangeResponseMetaExt } from './paginatedChangeResponseMetaExt';

export interface PaginatedChangeResponse {
  /** Schema-only class documenting the paginator envelope that wraps
  `ChangeResource::collection($paginator)`. Swagger refs this shape so Orval
  generates the correct paginated response type for both change-monitor
  endpoints.

  This file holds no runtime behaviour — `ChangeResource` itself performs
  the per-row transformation; the controller adds `meta_ext` via
  `additional(...)`. */
  data: ChangeResource[];
  links?: PaginatedChangeResponseLinks;
  meta: PaginatedChangeResponseMeta;
  meta_ext?: PaginatedChangeResponseMetaExt;
}
