/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { PublisherSearchResultResourcePlatform } from './publisherSearchResultResourcePlatform';
import type { PublisherSearchResultResourceSampleAppsItem } from './publisherSearchResultResourceSampleAppsItem';

export interface PublisherSearchResultResource {
  external_id: string;
  name: string;
  /** @nullable */
  url?: string | null;
  platform: PublisherSearchResultResourcePlatform;
  app_count?: number;
  sample_apps?: PublisherSearchResultResourceSampleAppsItem[];
}
