/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { PublisherPlatform } from './publisherPlatform';

export interface Publisher {
  id: number;
  name: string;
  /** @nullable */
  external_id?: string | null;
  platform: PublisherPlatform;
  /** @nullable */
  url?: string | null;
}
