/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { RatingSummaryResourceBreakdown } from './ratingSummaryResourceBreakdown';
import type { RatingSummaryResourceTrend } from './ratingSummaryResourceTrend';

export interface RatingSummaryResource {
  /** Expects the underlying resource to be an associative array of the form:
    ['latest' => ?AppMetric, 'baseline' => ?AppMetric]

  `latest` is the most recent metric row for the relevant country.
  `baseline` is the metric row used as the 30-day comparison anchor (or null
  when no such row exists). */
  rating: number;
  rating_count: number;
  /** @nullable */
  breakdown: RatingSummaryResourceBreakdown;
  trend: RatingSummaryResourceTrend;
}
