/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { SearchAppsPlatform } from './searchAppsPlatform';

export type SearchAppsParams = {
/**
 * @minLength 2
 * @maxLength 100
 */
term: string;
platform: SearchAppsPlatform;
/**
 * @minLength 2
 * @maxLength 2
 */
country_code?: string;
'exclude_external_ids[]'?: string[];
};
