/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { SearchPublishersPlatform } from './searchPublishersPlatform';

export type SearchPublishersParams = {
/**
 * @minLength 2
 */
term: string;
platform: SearchPublishersPlatform;
/**
 * @minLength 2
 * @maxLength 2
 */
country_code?: string;
};
