/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { StoreListingScreenshotsItem } from './storeListingScreenshotsItem';

export interface StoreListing {
  id: number;
  /** @nullable */
  version_id?: number | null;
  locale: string;
  title?: string;
  /** @nullable */
  subtitle?: string | null;
  description?: string;
  /** @nullable */
  promotional_text?: string | null;
  /** @nullable */
  whats_new?: string | null;
  /** @nullable */
  icon_url?: string | null;
  /** @nullable */
  screenshots?: StoreListingScreenshotsItem[] | null;
  price?: number;
  /** @nullable */
  currency?: string | null;
  /** @nullable */
  video_url?: string | null;
  fetched_at?: string;
}
