/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Platform of the competitor. Defaults to the parent app's platform when omitted.
 */
export type StoreCompetitorRequestCompetitorPlatform = typeof StoreCompetitorRequestCompetitorPlatform[keyof typeof StoreCompetitorRequestCompetitorPlatform];


export const StoreCompetitorRequestCompetitorPlatform = {
  ios: 'ios',
  android: 'android',
} as const;
