/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type StoreCategoryResourceType = typeof StoreCategoryResourceType[keyof typeof StoreCategoryResourceType] | null;


export const StoreCategoryResourceType = {
  app: 'app',
  game: 'game',
  magazine: 'magazine',
} as const;
