/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */

export interface StoreListingChange {
  id?: number;
  /** @nullable */
  version_id?: number | null;
  locale?: string;
  field_changed?: string;
  /** @nullable */
  old_value?: string | null;
  /** @nullable */
  new_value?: string | null;
  detected_at?: string;
}
