/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */

export interface StoreAppResource {
  external_id: string;
  name: string;
  /** @nullable */
  icon_url?: string | null;
  /** @nullable */
  rating?: number | null;
  /** @nullable */
  rating_count?: number | null;
  is_free?: boolean;
  /** @nullable */
  category?: string | null;
  is_tracked?: boolean;
}
