/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { SyncStatusResourceCurrentStep } from './syncStatusResourceCurrentStep';
import type { SyncStatusResourceFailedItemsItem } from './syncStatusResourceFailedItemsItem';
import type { SyncStatusResourceProgress } from './syncStatusResourceProgress';
import type { SyncStatusResourceStatus } from './syncStatusResourceStatus';

export interface SyncStatusResource {
  app_id?: number;
  status?: SyncStatusResourceStatus;
  /** @nullable */
  current_step?: SyncStatusResourceCurrentStep;
  progress?: SyncStatusResourceProgress;
  failed_items?: SyncStatusResourceFailedItemsItem[];
  failed_items_count?: number;
  /** @nullable */
  error_message?: string | null;
  /** @nullable */
  job_id?: string | null;
  /** @nullable */
  started_at?: string | null;
  /** @nullable */
  completed_at?: string | null;
  /** @nullable */
  next_retry_at?: string | null;
  /** @nullable */
  elapsed_ms?: number | null;
}
