/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type SyncStatusResourceCurrentStep = typeof SyncStatusResourceCurrentStep[keyof typeof SyncStatusResourceCurrentStep] | null;


export const SyncStatusResourceCurrentStep = {
  identity: 'identity',
  listings: 'listings',
  metrics: 'metrics',
  finalize: 'finalize',
  reconciling: 'reconciling',
} as const;
