/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { SyncStatusCurrentStep } from './syncStatusCurrentStep';
import type { SyncStatusFailedItemsItem } from './syncStatusFailedItemsItem';
import type { SyncStatusStatus } from './syncStatusStatus';

export interface SyncStatus {
  id: number;
  app_id: number;
  status: SyncStatusStatus;
  /** @nullable */
  current_step?: SyncStatusCurrentStep;
  progress_done?: number;
  progress_total?: number;
  /** @nullable */
  failed_items?: SyncStatusFailedItemsItem[] | null;
  /** @nullable */
  error_message?: string | null;
  /** @nullable */
  job_id?: string | null;
  /** @nullable */
  started_at?: string | null;
  /** @nullable */
  completed_at?: string | null;
  /** @nullable */
  next_retry_at?: string | null;
  created_at?: string;
  updated_at?: string;
}
