/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */

export type SyncStatusResourceFailedItemsItemType = typeof SyncStatusResourceFailedItemsItemType[keyof typeof SyncStatusResourceFailedItemsItemType];


export const SyncStatusResourceFailedItemsItemType = {
  listing: 'listing',
  metric: 'metric',
} as const;
