/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenApps by MBZA API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */

export interface User {
  id: number;
  name: string;
  email: string;
  /** @nullable */
  email_verified_at?: string | null;
  created_at?: string;
  updated_at?: string;
}
